// Code generated by qtc from "column_type.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line column_type.qtpl:1
package tpl

//line column_type.qtpl:2
import (
	"github.com/iancoleman/strcase"
	"github.com/ruslanBik4/dbEngine/dbEngine"
)

//line column_type.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line column_type.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line column_type.qtpl:9
type ColumnType struct {
	name    string
	sName   string
	columns []dbEngine.Column
}

func NewColumnType(table dbEngine.Table) *ColumnType {
	return &ColumnType{
		name:    strcase.ToCamel(table.Name()),
		sName:   table.Name(),
		columns: table.Columns(),
	}
}

//line column_type.qtpl:23
func (c *ColumnType) StreamColumnType(qw422016 *qt422016.Writer) {
//line column_type.qtpl:23
	qw422016.N().S(`
// `)
//line column_type.qtpl:24
	qw422016.E().S(c.name)
//line column_type.qtpl:24
	qw422016.N().S(`PsqlType represents the implicit PostgreSQL composite (row) type
// of table '`)
//line column_type.qtpl:25
	qw422016.E().S(c.sName)
//line column_type.qtpl:25
	qw422016.N().S(`' - the type Postgres creates automatically for every
// table, used when the whole row is selected as a single composite value
// (e.g. `)
//line column_type.qtpl:25
	qw422016.N().S("`")
//line column_type.qtpl:25
	qw422016.N().S(`SELECT t FROM `)
//line column_type.qtpl:27
	qw422016.E().S(c.sName)
//line column_type.qtpl:27
	qw422016.N().S(` t`)
//line column_type.qtpl:27
	qw422016.N().S("`")
//line column_type.qtpl:27
	qw422016.N().S(`).
//
// It implements the pgx v5 pgtype.Codec-related interfaces (PlanScan/ScanIndex/Scan)
// so pgx can decode it directly. This replaces the old pgx v4 pgtype.Value/AssignTo/
// DecodeBinary(ci *pgtype.ConnInfo, ...) approach, which no longer exists in pgx v5.
type (
	`)
//line column_type.qtpl:33
	qw422016.E().S(c.name)
//line column_type.qtpl:33
	qw422016.N().S(`PsqlType struct {
		`)
//line column_type.qtpl:34
	qw422016.E().S(c.name)
//line column_type.qtpl:34
	qw422016.N().S(`Fields
		Valid bool
	}
)

// GetFields implement dbEngine.RowScanner interface
func (r *`)
//line column_type.qtpl:40
	qw422016.E().S(c.name)
//line column_type.qtpl:40
	qw422016.N().S(`PsqlType) GetFields(columns []dbEngine.Column) []any {
	v := make([]any, len(columns))
	for i, col := range columns {
		switch name := col.Name(); name {
		case "`)
//line column_type.qtpl:44
	qw422016.E().S(c.sName)
//line column_type.qtpl:44
	qw422016.N().S(`":
			v[i] = r
		default:
			v[i] = r.RefColValue(name)
		}
	}

	return v
}

// FormatSupported implement pgtype.Codec interface: only binary composite decoding is supported
func (dst *`)
//line column_type.qtpl:55
	qw422016.E().S(c.name)
//line column_type.qtpl:55
	qw422016.N().S(`PsqlType) FormatSupported(format int16) bool {
	return format == pgtype.BinaryFormatCode
}

func (dst *`)
//line column_type.qtpl:59
	qw422016.E().S(c.name)
//line column_type.qtpl:59
	qw422016.N().S(`PsqlType) PreferredFormat() int16 {
	return pgtype.BinaryFormatCode
}

// PlanEncode implement pgtype.Codec interface: lets this row type be used as a
// query argument (e.g. `)
//line column_type.qtpl:59
	qw422016.N().S("`")
//line column_type.qtpl:59
	qw422016.N().S(`SELECT * FROM some_func($1::`)
//line column_type.qtpl:64
	qw422016.E().S(c.sName)
//line column_type.qtpl:64
	qw422016.N().S(`)`)
//line column_type.qtpl:64
	qw422016.N().S("`")
//line column_type.qtpl:64
	qw422016.N().S(`).
func (dst *`)
//line column_type.qtpl:65
	qw422016.E().S(c.name)
//line column_type.qtpl:65
	qw422016.N().S(`PsqlType) PlanEncode(m *pgtype.Map, oid uint32, format int16, value any) pgtype.EncodePlan {
	if _, ok := value.(pgtype.CompositeIndexGetter); !ok {
		return nil
		}
	if format != pgtype.BinaryFormatCode {
		return nil
	}

	fieldOIDs := make([]uint32, `)
//line column_type.qtpl:73
	qw422016.N().D(len(c.columns))
//line column_type.qtpl:73
	qw422016.N().S(`)
	`)
//line column_type.qtpl:74
	for i, col := range c.columns {
//line column_type.qtpl:74
		qw422016.N().S(`
	if typ, ok := m.TypeForName("`)
//line column_type.qtpl:75
		qw422016.E().S(col.Type())
//line column_type.qtpl:75
		qw422016.N().S(`"); ok {
		fieldOIDs[`)
//line column_type.qtpl:76
		qw422016.N().D(i)
//line column_type.qtpl:76
		qw422016.N().S(`] = typ.OID
	}
	`)
//line column_type.qtpl:78
	}
//line column_type.qtpl:78
	qw422016.N().S(`

	return &`)
//line column_type.qtpl:80
	qw422016.E().S(c.name)
//line column_type.qtpl:80
	qw422016.N().S(`PsqlTypeEncodePlan{m: m, fieldOIDs: fieldOIDs}
}

// IsNull implement pgtype.CompositeIndexGetter interface
func (dst *`)
//line column_type.qtpl:84
	qw422016.E().S(c.name)
//line column_type.qtpl:84
	qw422016.N().S(`PsqlType) IsNull() bool {
	return !dst.Valid
}

// Index implement pgtype.CompositeIndexGetter interface
func (dst *`)
//line column_type.qtpl:89
	qw422016.E().S(c.name)
//line column_type.qtpl:89
	qw422016.N().S(`PsqlType) Index(i int) any {
	switch i {
	`)
//line column_type.qtpl:91
	for i, col := range c.columns {
//line column_type.qtpl:91
		qw422016.N().S(`case `)
//line column_type.qtpl:91
		qw422016.N().D(i)
//line column_type.qtpl:91
		qw422016.N().S(`:
		return dst.ColValue("`)
//line column_type.qtpl:92
		qw422016.E().S(col.Name())
//line column_type.qtpl:92
		qw422016.N().S(`")
	`)
//line column_type.qtpl:93
	}
//line column_type.qtpl:93
	qw422016.N().S(`
	default:
		panic("invalid index")
	}
	}

// `)
//line column_type.qtpl:99
	qw422016.E().S(c.name)
//line column_type.qtpl:99
	qw422016.N().S(`PsqlTypeEncodePlan builds the composite wire format for
// `)
//line column_type.qtpl:100
	qw422016.E().S(c.name)
//line column_type.qtpl:100
	qw422016.N().S(`PsqlType, following the same builder pattern as pgtype.CompositeCodec's
// own encode plans.
type `)
//line column_type.qtpl:102
	qw422016.E().S(c.name)
//line column_type.qtpl:102
	qw422016.N().S(`PsqlTypeEncodePlan struct {
	m         *pgtype.Map
	fieldOIDs []uint32
}

func (plan *`)
//line column_type.qtpl:107
	qw422016.E().S(c.name)
//line column_type.qtpl:107
	qw422016.N().S(`PsqlTypeEncodePlan) Encode(value any, buf []byte) ([]byte, error) {
	getter := value.(pgtype.CompositeIndexGetter)
	if getter.IsNull() {
		return nil, nil
	}

	b := pgtype.NewCompositeBinaryBuilder(plan.m, buf)
	for i, oid := range plan.fieldOIDs {
		b.AppendValue(oid, getter.Index(i))
	}

	return b.Finish()
}

// PlanScan implement pgtype.Codec interface. dst here is only a stateless method
// holder for Scan (below) - see the note on Scan for why it never reads its own
// fields.
func (dst *`)
//line column_type.qtpl:124
	qw422016.E().S(c.name)
//line column_type.qtpl:124
	qw422016.N().S(`PsqlType) PlanScan(m *pgtype.Map, oid uint32, format int16, target any) pgtype.ScanPlan {
	if _, ok := target.(*`)
//line column_type.qtpl:125
	qw422016.E().S(c.name)
//line column_type.qtpl:125
	qw422016.N().S(`PsqlType); !ok {
		return nil
	}

	return dst
}

func (dst *`)
//line column_type.qtpl:132
	qw422016.E().S(c.name)
//line column_type.qtpl:132
	qw422016.N().S(`PsqlType) DecodeDatabaseSQLValue(m *pgtype.Map, oid uint32, format int16, src []byte) (driver.Value, error) {
	if src == nil {
		return nil, nil
	}

	switch format {
	case pgtype.TextFormatCode:
		return string(src), nil

	case pgtype.BinaryFormatCode:
		buf := make([]byte, len(src))
		copy(buf, src)
		return buf, nil

		default:
		return nil, fmt.Errorf("unknown format code %d", format)
	}
}

func (dst *`)
//line column_type.qtpl:151
	qw422016.E().S(c.name)
//line column_type.qtpl:151
	qw422016.N().S(`PsqlType) DecodeValue(m *pgtype.Map, oid uint32, format int16, src []byte) (any, error) {
	if src == nil {
		return nil, nil
	}
	if format != pgtype.BinaryFormatCode {
		return nil, fmt.Errorf("DecodeValue: unsupported format code %d", format)
	}

	values := make(map[string]any, `)
//line column_type.qtpl:159
	qw422016.N().D(len(c.columns))
//line column_type.qtpl:159
	qw422016.N().S(`)
	scanner := pgtype.NewCompositeBinaryScanner(m, src)

	`)
//line column_type.qtpl:162
	for _, col := range c.columns {
//line column_type.qtpl:162
		qw422016.N().S(`
	if !scanner.Next() {
		return nil, scanner.Err()
			}
	{
		var v any
		fieldPlan := m.PlanScan(scanner.OID(), pgtype.BinaryFormatCode, &v)
		if fieldPlan == nil {
			return nil, fmt.Errorf("unable to scan OID %d in binary format into field %q", scanner.OID(), "`)
//line column_type.qtpl:170
		qw422016.E().S(col.Name())
//line column_type.qtpl:170
		qw422016.N().S(`")
		}
		if err := fieldPlan.Scan(scanner.Bytes(), &v); err != nil {
			return nil, err
		}
		values["`)
//line column_type.qtpl:175
		qw422016.E().S(col.Name())
//line column_type.qtpl:175
		qw422016.N().S(`"] = v
	}
	`)
//line column_type.qtpl:177
	}
//line column_type.qtpl:177
	qw422016.N().S(`

	return values, scanner.Err()
}

// ScanIndex implement pgtype.ScanPlan interface: maps each positional composite
// field (Postgres sends them in table-column/attnum order) to the matching struct field.
func (dst *`)
//line column_type.qtpl:184
	qw422016.E().S(c.name)
//line column_type.qtpl:184
	qw422016.N().S(`PsqlType) ScanIndex(i int) any {
	switch i {
	`)
//line column_type.qtpl:186
	for i, col := range c.columns {
//line column_type.qtpl:186
		qw422016.N().S(`case `)
//line column_type.qtpl:186
		qw422016.N().D(i)
//line column_type.qtpl:186
		qw422016.N().S(`:
		return dst.RefColValue("`)
//line column_type.qtpl:187
		qw422016.E().S(col.Name())
//line column_type.qtpl:187
		qw422016.N().S(`")
	`)
//line column_type.qtpl:188
	}
//line column_type.qtpl:188
	qw422016.N().S(`
	default:
		panic("invalid index")
}
}

// Scan implement pgtype.ScanPlan interface. PlanScan (above) hands back this same
// method regardless of which *`)
//line column_type.qtpl:195
	qw422016.E().S(c.name)
//line column_type.qtpl:195
	qw422016.N().S(`PsqlType it happens to be called on - a
// registered Codec is a single shared instance reused for every row/column of this
// OID, so the actual per-call destination is always the `)
//line column_type.qtpl:195
	qw422016.N().S("`")
//line column_type.qtpl:195
	qw422016.N().S(`target`)
//line column_type.qtpl:195
	qw422016.N().S("`")
//line column_type.qtpl:195
	qw422016.N().S(` argument, never
// this method's own receiver.
func (dst *`)
//line column_type.qtpl:199
	qw422016.E().S(c.name)
//line column_type.qtpl:199
	qw422016.N().S(`PsqlType) Scan(src []byte, target any) error {
	dest, ok := target.(*`)
//line column_type.qtpl:200
	qw422016.E().S(c.name)
//line column_type.qtpl:200
	qw422016.N().S(`PsqlType)
	if !ok {
		return fmt.Errorf("Scan: unsupported target type %T", target)
	}

	dest.Valid = false
	if len(src) == 0 {
		return nil
	}

	m := pgtype.NewMap()
	c := pgtype.NewCompositeBinaryScanner(m, src)

	for i := range c.FieldCount() {
		//	    reach end of elements
		if !c.Next() {
		return nil
	}

		field := dest.ScanIndex(i)
		fieldPlan := m.PlanScan(c.OID(), pgtype.BinaryFormatCode, field)
		if fieldPlan == nil {
			return fmt.Errorf("unable to scan OID %d in binary format into field %d", c.OID(), i)
		}

		if err := fieldPlan.Scan(c.Bytes(), field); err != nil {
		return err
	}
	}

	dest.Valid = true

	return nil
}

// Value implements the [database/sql/driver.Valuer] interface, kept only for
// interop with plain database/sql code paths. Native pgx v5 query execution
// goes through PlanEncode/PlanScan above instead.
func (src *`)
//line column_type.qtpl:238
	qw422016.E().S(c.name)
//line column_type.qtpl:238
	qw422016.N().S(`PsqlType) Value() (driver.Value, error) {
	if !src.Valid {
		return nil, nil
}

	return src, nil
}

`)
//line column_type.qtpl:247
	stringFmt := ""
	for i, col := range c.columns {
		if i > 0 {
			stringFmt += ", "
		}
		stringFmt += col.Name() + ": %v"
	}

//line column_type.qtpl:254
	qw422016.N().S(`
// String implements fmt.Stringer by reading struct fields directly (not
// ColValue's name-switch, not a re-decode) - fmt.Sprintf("%v", ...) picks
// this up automatically both for a single value (see Value() above, which
// hands fmt this same *`)
//line column_type.qtpl:258
	qw422016.E().S(c.name)
//line column_type.qtpl:258
	qw422016.N().S(`PsqlType back) and for each element when
// formatting a []*`)
//line column_type.qtpl:259
	qw422016.E().S(c.name)
//line column_type.qtpl:259
	qw422016.N().S(`PsqlType slice, so callers like
// ToStandardColumnValueType need no type-specific or reflect-based handling
// of their own - and this itself never reflects, since every field access
// below is resolved at compile time.
func (dst *`)
//line column_type.qtpl:263
	qw422016.E().S(c.name)
//line column_type.qtpl:263
	qw422016.N().S(`PsqlType) String() string {
	if !dst.Valid {
		return ""
	}

	return fmt.Sprintf("`)
//line column_type.qtpl:268
	qw422016.N().S(stringFmt)
//line column_type.qtpl:268
	qw422016.N().S(`",
`)
//line column_type.qtpl:269
	for _, col := range c.columns {
//line column_type.qtpl:269
		qw422016.N().S(`		dst.`)
//line column_type.qtpl:270
		qw422016.E().S(strcase.ToCamel(col.Name()))
//line column_type.qtpl:270
		qw422016.N().S(`,
`)
//line column_type.qtpl:271
	}
//line column_type.qtpl:271
	qw422016.N().S(`	)
}
`)
//line column_type.qtpl:274
}

//line column_type.qtpl:274
func (c *ColumnType) WriteColumnType(qq422016 qtio422016.Writer) {
//line column_type.qtpl:274
	qw422016 := qt422016.AcquireWriter(qq422016)
//line column_type.qtpl:274
	c.StreamColumnType(qw422016)
//line column_type.qtpl:274
	qt422016.ReleaseWriter(qw422016)
//line column_type.qtpl:274
}

//line column_type.qtpl:274
func (c *ColumnType) ColumnType() string {
//line column_type.qtpl:274
	qb422016 := qt422016.AcquireByteBuffer()
//line column_type.qtpl:274
	c.WriteColumnType(qb422016)
//line column_type.qtpl:274
	qs422016 := string(qb422016.B)
//line column_type.qtpl:274
	qt422016.ReleaseByteBuffer(qb422016)
//line column_type.qtpl:274
	return qs422016
//line column_type.qtpl:274
}
