// Code generated by qtc from "database_tpl.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line database_tpl.qtpl:1
package tpl

//line database_tpl.qtpl:1
import (
	"fmt"

	"github.com/iancoleman/strcase"
	"github.com/ruslanBik4/dbEngine/dbEngine"
)

//line database_tpl.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line database_tpl.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line database_tpl.qtpl:10
type DatabaseTpl struct {
	Types    map[string]string
	db       *dbEngine.DB
	Packages []string
}

func NewDatabaseTpl(db *dbEngine.DB) *DatabaseTpl {
	return &DatabaseTpl{
		Types: make(map[string]string),
		db:    db,
	}
}

//line database_tpl.qtpl:23
func (t *DatabaseTpl) StreamCreateDatabase(qw422016 *qt422016.Writer) {
//line database_tpl.qtpl:23
	qw422016.N().S(`
// Code generated by dbEngine-gen-go. DO NOT EDIT.
// versions:
// 	dbEngine v1.1.6
// source: %s %s
package db

import (
	"bytes"
	"fmt"
	"time"
	"strings"
`)
//line database_tpl.qtpl:35
	for _, lib := range t.Packages {
//line database_tpl.qtpl:35
		qw422016.N().S(`"`)
//line database_tpl.qtpl:35
		qw422016.E().S(lib)
//line database_tpl.qtpl:35
		qw422016.N().S(`"
`)
//line database_tpl.qtpl:36
	}
//line database_tpl.qtpl:36
	qw422016.N().S(`
	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"

	"github.com/ruslanBik4/logs"
	"github.com/ruslanBik4/dbEngine/dbEngine"
    "github.com/ruslanBik4/dbEngine/dbEngine/psql"

	"golang.org/x/net/context"
	"github.com/pkg/errors"
)
`)
//line database_tpl.qtpl:48
	for name, typ := range t.db.Types {
//line database_tpl.qtpl:48
		StreamCreateTypeInterface(qw422016, typ, strcase.ToCamel(name), name, t.Types[name])
//line database_tpl.qtpl:48
		qw422016.N().S(`
`)
//line database_tpl.qtpl:49
	}
//line database_tpl.qtpl:49
	qw422016.N().S(`
// Database is root interface for operation for %s.%s
type Database struct {
	*dbEngine.DB
	CreateAt time.Time
}
// NewDatabase create new Database with minimal necessary handlers
func NewDatabase(ctx context.Context, noticeHandler pgconn.NoticeHandler, channelHandler pgconn.NotificationHandler, channels ...string) (*Database, error) {
	if noticeHandler == nil {
		noticeHandler = printNotice
	}
	conn := psql.NewConn(nil, nil, noticeHandler, channels...)
	if channelHandler != nil {
		conn.ChannelHandler = channelHandler
	}

	DB, err := dbEngine.NewDB(ctx, conn)
	if err != nil {
		logs.ErrorLog(err, "")
		return nil, err
	}

	return &Database{DB, time.Now()}, nil
}
// PsqlConn return connection as *psql.Conn
// need for some low-level operation,
// invoke Conn.Select...(custom sql),
//        New{table_name}FromConn, etc.
func (d *Database) PsqlConn() *psql.Conn {
	return (d.Conn).(*psql.Conn)
}
`)
//line database_tpl.qtpl:81
	for name := range t.db.Tables {
//line database_tpl.qtpl:82
		t.StreamCreateTableConstructor(qw422016, strcase.ToCamel(name), name)
//line database_tpl.qtpl:82
		qw422016.N().S(`
`)
//line database_tpl.qtpl:83
	}
//line database_tpl.qtpl:83
	qw422016.N().S(`
`)
//line database_tpl.qtpl:85
}

//line database_tpl.qtpl:85
func (t *DatabaseTpl) WriteCreateDatabase(qq422016 qtio422016.Writer) {
//line database_tpl.qtpl:85
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:85
	t.StreamCreateDatabase(qw422016)
//line database_tpl.qtpl:85
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:85
}

//line database_tpl.qtpl:85
func (t *DatabaseTpl) CreateDatabase() string {
//line database_tpl.qtpl:85
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:85
	t.WriteCreateDatabase(qb422016)
//line database_tpl.qtpl:85
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:85
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:85
	return qs422016
//line database_tpl.qtpl:85
}

//line database_tpl.qtpl:87
func StreamCreateTypeInterface(qw422016 *qt422016.Writer, t dbEngine.Types, cName, name, typeCol string) {
//line database_tpl.qtpl:87
	qw422016.N().S(`// `)
//line database_tpl.qtpl:88
	qw422016.E().S(cName)
//line database_tpl.qtpl:88
	qw422016.N().S(` create new instance of type `)
//line database_tpl.qtpl:88
	qw422016.E().S(name)
//line database_tpl.qtpl:88
	qw422016.N().S(`
type `)
//line database_tpl.qtpl:89
	qw422016.E().S(cName)
//line database_tpl.qtpl:89
	qw422016.N().S(` struct {
`)
//line database_tpl.qtpl:90
	for name, tName := range t.Attr {
//line database_tpl.qtpl:90
		qw422016.N().S(`	`)
//line database_tpl.qtpl:91
		qw422016.E().S(strcase.ToCamel(name))
//line database_tpl.qtpl:91
		qw422016.N().S(fmt.Sprintf("\t\t\t%s\t", tName))
//line database_tpl.qtpl:91
		qw422016.N().S(``)
//line database_tpl.qtpl:91
		qw422016.N().S("`")
//line database_tpl.qtpl:91
		qw422016.N().S(`json:"`)
//line database_tpl.qtpl:91
		qw422016.E().S(name)
//line database_tpl.qtpl:91
		qw422016.N().S(`"`)
//line database_tpl.qtpl:91
		qw422016.N().S("`")
//line database_tpl.qtpl:91
		qw422016.N().S(`
`)
//line database_tpl.qtpl:92
	}
//line database_tpl.qtpl:92
	qw422016.N().S(`}

func (dst *`)
//line database_tpl.qtpl:95
	qw422016.E().S(cName)
//line database_tpl.qtpl:95
	qw422016.N().S(`) DecodeText(ci *pgtype.ConnInfo, src []byte) error {
	if len(src) == 0 {
		*dst = `)
//line database_tpl.qtpl:97
	qw422016.E().S(cName)
//line database_tpl.qtpl:97
	qw422016.N().S(`{}
		return nil
	}
	srcPart := bytes.Split(src[1:len(src)-1], []byte(","))
    *dst =  `)
//line database_tpl.qtpl:101
	qw422016.E().S(cName)
//line database_tpl.qtpl:101
	qw422016.N().S(`{
`)
//line database_tpl.qtpl:102
	for name, tName := range t.Attr {
//line database_tpl.qtpl:102
		qw422016.N().S(`		`)
//line database_tpl.qtpl:103
		qw422016.E().S(strcase.ToCamel(name))
//line database_tpl.qtpl:103
		qw422016.N().S(`: psql.Get`)
//line database_tpl.qtpl:103
		qw422016.E().S(strcase.ToCamel(tName))
//line database_tpl.qtpl:103
		qw422016.N().S(`FromByte(ci, srcPart[0], "`)
//line database_tpl.qtpl:103
		qw422016.E().S(name)
//line database_tpl.qtpl:103
		qw422016.N().S(`"),
`)
//line database_tpl.qtpl:104
	}
//line database_tpl.qtpl:104
	qw422016.N().S(`        },
}
`)
//line database_tpl.qtpl:107
}

//line database_tpl.qtpl:107
func WriteCreateTypeInterface(qq422016 qtio422016.Writer, t dbEngine.Types, cName, name, typeCol string) {
//line database_tpl.qtpl:107
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:107
	StreamCreateTypeInterface(qw422016, t, cName, name, typeCol)
//line database_tpl.qtpl:107
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:107
}

//line database_tpl.qtpl:107
func CreateTypeInterface(t dbEngine.Types, cName, name, typeCol string) string {
//line database_tpl.qtpl:107
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:107
	WriteCreateTypeInterface(qb422016, t, cName, name, typeCol)
//line database_tpl.qtpl:107
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:107
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:107
	return qs422016
//line database_tpl.qtpl:107
}

//line database_tpl.qtpl:109
func (t *DatabaseTpl) StreamCreateTableConstructor(qw422016 *qt422016.Writer, cName, name string) {
//line database_tpl.qtpl:109
	qw422016.N().S(`// New`)
//line database_tpl.qtpl:110
	qw422016.E().S(cName)
//line database_tpl.qtpl:110
	qw422016.N().S(` create new instance of table `)
//line database_tpl.qtpl:110
	qw422016.E().S(cName)
//line database_tpl.qtpl:110
	qw422016.N().S(`
func (d *Database) New`)
//line database_tpl.qtpl:111
	qw422016.E().S(cName)
//line database_tpl.qtpl:111
	qw422016.N().S(`(ctx context.Context) (*`)
//line database_tpl.qtpl:111
	qw422016.E().S(cName)
//line database_tpl.qtpl:111
	qw422016.N().S(`, error) {
	const name = "`)
//line database_tpl.qtpl:112
	qw422016.E().S(name)
//line database_tpl.qtpl:112
	qw422016.N().S(`"
	table, ok := d.Tables[name]
    if !ok {
		var err error
		table, err = New`)
//line database_tpl.qtpl:116
	qw422016.E().S(cName)
//line database_tpl.qtpl:116
	qw422016.N().S(`FromConn(ctx, d.PsqlConn())
		if err != nil {
			return nil, err
		}
		d.Tables[name] = table
    }

    return &`)
//line database_tpl.qtpl:123
	qw422016.E().S(cName)
//line database_tpl.qtpl:123
	qw422016.N().S(`{
		Table: table.(*psql.Table),
    }, nil
}
`)
//line database_tpl.qtpl:127
}

//line database_tpl.qtpl:127
func (t *DatabaseTpl) WriteCreateTableConstructor(qq422016 qtio422016.Writer, cName, name string) {
//line database_tpl.qtpl:127
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:127
	t.StreamCreateTableConstructor(qw422016, cName, name)
//line database_tpl.qtpl:127
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:127
}

//line database_tpl.qtpl:127
func (t *DatabaseTpl) CreateTableConstructor(cName, name string) string {
//line database_tpl.qtpl:127
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:127
	t.WriteCreateTableConstructor(qb422016, cName, name)
//line database_tpl.qtpl:127
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:127
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:127
	return qs422016
//line database_tpl.qtpl:127
}
