// Code generated by qtc from "database_tpl.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line database_tpl.qtpl:1
package tpl

//line database_tpl.qtpl:2
import (
	"fmt"
	"slices"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/ruslanBik4/dbEngine/dbEngine"
	"github.com/ruslanBik4/dbEngine/dbEngine/psql"
)

//line database_tpl.qtpl:13
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line database_tpl.qtpl:13
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line database_tpl.qtpl:13
func StreamHeader(qw422016 *qt422016.Writer, imports []string, title string) {
//line database_tpl.qtpl:13
	qw422016.N().S(`// Code generated by dbEngine-gen-go. DO NOT EDIT.
// Copyright https://github.com/ruslanBik4

/*
	Package db

DB implements interface for table, view and routines of Database
versions:

 	dbEngine v1.2.*

source: `)
//line database_tpl.qtpl:25
	qw422016.E().S(title)
//line database_tpl.qtpl:25
	qw422016.N().S(`
*/
package db

import (
`)
//line database_tpl.qtpl:30
	for _, lib := range imports {
//line database_tpl.qtpl:30
		qw422016.N().S(`	"`)
//line database_tpl.qtpl:31
		qw422016.E().S(lib)
//line database_tpl.qtpl:31
		qw422016.N().S(`"
`)
//line database_tpl.qtpl:32
	}
//line database_tpl.qtpl:32
	qw422016.N().S(`)
`)
//line database_tpl.qtpl:34
}

//line database_tpl.qtpl:34
func WriteHeader(qq422016 qtio422016.Writer, imports []string, title string) {
//line database_tpl.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:34
	StreamHeader(qw422016, imports, title)
//line database_tpl.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:34
}

//line database_tpl.qtpl:34
func Header(imports []string, title string) string {
//line database_tpl.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:34
	WriteHeader(qb422016, imports, title)
//line database_tpl.qtpl:34
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:34
	return qs422016
//line database_tpl.qtpl:34
}

//line database_tpl.qtpl:36
func (c *PackageBuilder) StreamCreateDatabase(qw422016 *qt422016.Writer, title string, imports, listTables, listRoutines []string) {
//line database_tpl.qtpl:37
	StreamHeader(qw422016, imports, title)
//line database_tpl.qtpl:37
	qw422016.N().S(`
type scanError interface {
	ScanValue(d any)
	Err() error
}

// ValueDecoder is a value that implements the text and binary encoding and decoding interfaces.
type ValueDecoder[T any] interface {
	pgtype.Codec
	New() T
}

type WrapArray[T ValueDecoder[T]] []T
/*
func (dst *WrapArray[T]) Scan(src any) error {
	if src == nil {
		*n = Numeric{}
		return nil
	}

	if src, ok := src.(string); ok {
		return scanPlanTextAnyToNumericScanner{}.Scan([]byte(src), n)
	}

	return fmt.Errorf("cannot scan %T", src)
}/*
func (dst *WrapArray[T]) DecodeText(ci *pgtype.ConnInfo, src []byte) (err error) {
	if len(src) == 0 {
		return nil
	}

	arr, err := pgtype.ParseUntypedTextArray(gotools.BytesToString(src))
	if err != nil {
		return err
	}

	if len(arr.Elements) == 0 {
		return nil
	}

	buf := make([]T, len(arr.Elements))
	for i, el := range arr.Elements {
		buf[i] = T.New(buf[i])
		if err := buf[i].DecodeText(ci, gotools.StringToBytes(el)); err != nil {
			return err
		}
	}

	*dst = buf

	return nil
}

func (dst *WrapArray[T]) DecodeBinary(ci *pgtype.ConnInfo, src []byte) (err error) {
	if len(src) == 0 {
		return nil
	}

	arr, err := pgtype.ParseUntypedTextArray(gotools.BytesToString(src))
	if err != nil {
		return err
	}

	if len(arr.Elements) == 0 {
		return nil
	}

	buf := make([]T, len(arr.Elements))
	for i, el := range arr.Elements {
		buf[i] = T.New(buf[i])
		if err := buf[i].DecodeBinary(ci, gotools.StringToBytes(el)); err != nil {
			return err
		}
	}

	*dst = buf

	return nil
}*/
`)
//line database_tpl.qtpl:116
	hasCitext := false

//line database_tpl.qtpl:116
	qw422016.N().S(`

`)
//line database_tpl.qtpl:118
	for _, name := range c.types {
//line database_tpl.qtpl:119
		if name != "citext" {
//line database_tpl.qtpl:119
			c.StreamCreateTypeInterface(qw422016, c.DB.Types[name], strcase.ToCamel(name), name, c.Types[name])
//line database_tpl.qtpl:119
			qw422016.N().S(`
`)
//line database_tpl.qtpl:120
		} else {
//line database_tpl.qtpl:120
			qw422016.N().S(`
type CitextArray []string

func (dst CitextArray) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBufferString("[")
	buf.WriteString(strings.Join(dst, ","))
	buf.WriteString("]")

	return buf.Bytes(), nil
}

var customTypes = map[string]*pgtype.Type{
	"citext": {
		Codec: pgtype.TextCodec{},
		Name:  "citext",
	},
	"_citext": {
		Codec: &pgtype.ArrayCodec{ElementType: &pgtype.Type{
			Codec: pgtype.TextCodec{},
			Name:  "citext",

		}},
		Name:  "[]string",
	},
}

var initCustomTypes bool

const sqlGetTypes = "SELECT typname, oid FROM pg_type WHERE typname::text=ANY($1)"

func getOidCustomTypes(ctx context.Context, conn *pgx.Conn) error {
	params := make([]string, 0, len(customTypes))
	for name := range customTypes {
		params = append(params, name)
	}

	rows, err := conn.Query(ctx, sqlGetTypes, params)
	if err != nil {
		return err
	}

	for rows.Next() {
		var name string
		var oid uint32
		err = rows.Scan(&name, &oid)
		if err != nil {
			return err
		}
		if c, ok := customTypes[name]; ok && c.Codec == (pgtype.Codec)(nil) {
			c.Codec = &pgtype.ArrayCodec{}
			c.OID = oid
			logs.StatusLog("(%s,%v, %T) ", name, c.OID, c.Codec)
		} else if ok {
			customTypes[name].OID = oid
			logs.StatusLog("%s, %v. DB registered type (name, oid): %s %v",
				conn.PgConn().PID(), conn.PgConn().CustomData(), c.Name, c.OID)
		}
	}

	if rows.Err() != nil {
		logs.ErrorLog(rows.Err(), " cannot get oid for customTypes")
	}

	return err
}

// afterConnect create need types & register on conn
func afterConnect(ctx context.Context, conn *pgx.Conn) error {
	// Override registered handler for point
	if !initCustomTypes {
		err := getOidCustomTypes(ctx, conn)
		if err != nil {
			return err
		}

		initCustomTypes = true
	}

	for _, val := range customTypes {
		conn.TypeMap().RegisterType(val)
	}

	return nil
}
`)
//line database_tpl.qtpl:204
			hasCitext = true

//line database_tpl.qtpl:204
			qw422016.N().S(`
`)
//line database_tpl.qtpl:205
		}
//line database_tpl.qtpl:205
		qw422016.N().S(`
`)
//line database_tpl.qtpl:206
	}
//line database_tpl.qtpl:206
	qw422016.N().S(`// Database is root interface for operation for %s.%s
type Database struct {
	*dbEngine.DB
	CreateAt time.Time
}

// NewDatabase create new Database with minimal necessary handlers
func NewDatabase(ctx context.Context, noticeHandler pgconn.NoticeHandler, channelHandler pgconn.NotificationHandler, channels ...string) (*Database, error) {
	if noticeHandler == nil {
		noticeHandler = psql.PrintNotice
	}
	conn := psql.NewConnWithOptions(
`)
//line database_tpl.qtpl:219
	if hasCitext {
//line database_tpl.qtpl:219
		qw422016.N().S(`psql.AfterConnect(afterConnect),`)
//line database_tpl.qtpl:219
	}
//line database_tpl.qtpl:219
	qw422016.N().S(`		psql.NoticeHandler(noticeHandler),
		psql.ChannelHandler(channelHandler),
		psql.Channels(channels...),
	)

	DB, err := dbEngine.NewDB(ctx, conn)
	if err != nil {
		logs.ErrorLog(err, "new DB")
		return nil, err
	}

	return &Database{DB, time.Now()}, nil
}

func (DB *Database) Notify(ctx context.Context, ch, mess string) string {
	res := ""
	err := DB.Conn.SelectOneAndScan(ctx, &res, "SELECT pg_notify($1,$2)::varchar", ch, mess)
	if err != nil {
		logs.ErrorLog(err, "SELECT pg_notify(%s, %s)", ch, mess)
	} else {
		logs.DebugLog("send notify '%s' in channel '%s': %s", mess, ch, res)
	}

	return res
}

// PsqlConn return connection as *psql.Conn
// need for some low-level operation,
// invoke Conn.Select...(custom sql),
//        New{table_name}FromConn, etc.
func (d *Database) PsqlConn() *psql.Conn {
	return (d.Conn).(*psql.Conn)
}

// SaveDataToTable
func (d *Database) SaveDataToTable(ctx context.Context, table string, r io.Reader, columns ... string) (int64, error) {
	switch table {
`)
//line database_tpl.qtpl:257
	for _, name := range listTables {
//line database_tpl.qtpl:257
		qw422016.N().S(`	`)
//line database_tpl.qtpl:258
		if c.DB.Tables[name].(*psql.Table).Type == "BASE TABLE" {
//line database_tpl.qtpl:258
			qw422016.N().S(`
	case "`)
//line database_tpl.qtpl:259
			qw422016.E().S(name)
//line database_tpl.qtpl:259
			qw422016.N().S(`":
		t, err := d.New`)
//line database_tpl.qtpl:260
			qw422016.E().S(strcase.ToCamel(name))
//line database_tpl.qtpl:260
			qw422016.N().S(`(ctx)
		if err != nil {
			return -1, err
		}

		err = gob.NewDecoder(r).Decode(&t.DoCopyPoll)
		if err != nil {
			return -1, err
		}

		t.doCopyPoolCount = len(t.DoCopyPoll)
		t.doCopyPoolColumns = columns

		return t.doCopy(ctx)
	`)
//line database_tpl.qtpl:274
		}
//line database_tpl.qtpl:274
		qw422016.N().S(`
`)
//line database_tpl.qtpl:275
	}
//line database_tpl.qtpl:275
	qw422016.N().S(`	default:
		return -1, dbEngine.NewErrNotFoundTable(table)
	}
}
`)
//line database_tpl.qtpl:280
	for _, name := range listTables {
//line database_tpl.qtpl:280
		StreamCreateTableConstructor(qw422016, strcase.ToCamel(name), name)
//line database_tpl.qtpl:280
	}
//line database_tpl.qtpl:281
	for _, name := range listRoutines {
//line database_tpl.qtpl:281
		c.StreamCreateRoutinesInvoker(qw422016, c.Routines[name].(*psql.Routine), name)
//line database_tpl.qtpl:281
	}
//line database_tpl.qtpl:282
}

//line database_tpl.qtpl:282
func (c *PackageBuilder) WriteCreateDatabase(qq422016 qtio422016.Writer, title string, imports, listTables, listRoutines []string) {
//line database_tpl.qtpl:282
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:282
	c.StreamCreateDatabase(qw422016, title, imports, listTables, listRoutines)
//line database_tpl.qtpl:282
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:282
}

//line database_tpl.qtpl:282
func (c *PackageBuilder) CreateDatabase(title string, imports, listTables, listRoutines []string) string {
//line database_tpl.qtpl:282
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:282
	c.WriteCreateDatabase(qb422016, title, imports, listTables, listRoutines)
//line database_tpl.qtpl:282
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:282
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:282
	return qs422016
//line database_tpl.qtpl:282
}

//line database_tpl.qtpl:284
func (c *PackageBuilder) StreamCreateTypeInterface(qw422016 *qt422016.Writer, t dbEngine.Types, typeName, name, typeCol string) {
//line database_tpl.qtpl:285
	if len(t.Enumerates) == 0 && len(t.Attr) > 0 && t.Attr[0].Name != "domain" {
//line database_tpl.qtpl:285
		qw422016.N().S(`// `)
//line database_tpl.qtpl:286
		qw422016.E().S(typeName)
//line database_tpl.qtpl:286
		qw422016.N().S(` create new instance of type `)
//line database_tpl.qtpl:286
		qw422016.E().S(name)
//line database_tpl.qtpl:286
		qw422016.N().S(`
//  add Rows interface
type `)
//line database_tpl.qtpl:288
		qw422016.E().S(typeName)
//line database_tpl.qtpl:288
		qw422016.N().S(` struct {
    `)
//line database_tpl.qtpl:290
		maxName := len(slices.MaxFunc(t.Attr, func(a, b dbEngine.TypesAttr) int {
			return len(a.Name) - len(b.Name)
		}).Name)
		maxType := len(slices.MaxFunc(t.Attr, func(a, b dbEngine.TypesAttr) int {
			return len(a.Type) - len(b.Type)
		}).Type)

//line database_tpl.qtpl:296
		qw422016.N().S(`
`)
//line database_tpl.qtpl:297
		for _, attr := range t.Attr {
//line database_tpl.qtpl:297
			qw422016.N().S(`	`)
//line database_tpl.qtpl:298
			qw422016.N().S(fmt.Sprintf("%-*s\t\t%-*s\t `json:\"%s", maxName, strcase.ToCamel(attr.Name), maxType, attr.Type, attr.Name))
//line database_tpl.qtpl:298
			if !attr.NotOmited() {
//line database_tpl.qtpl:298
				qw422016.N().S(`,omitempty`)
//line database_tpl.qtpl:298
			}
//line database_tpl.qtpl:298
			qw422016.N().S(`"`)
//line database_tpl.qtpl:298
			qw422016.N().S("`")
//line database_tpl.qtpl:298
			qw422016.N().S(`
`)
//line database_tpl.qtpl:299
		}
//line database_tpl.qtpl:300
		if t.Type == 'r' {
//line database_tpl.qtpl:300
			qw422016.N().S(`	LowerType pgtype.BoundType
	UpperType pgtype.BoundType
`)
//line database_tpl.qtpl:303
		}
//line database_tpl.qtpl:303
		qw422016.N().S(`}

// New implement ValueDecoder[T any] interface
func (dst *`)
//line database_tpl.qtpl:307
		qw422016.E().S(typeName)
//line database_tpl.qtpl:307
		qw422016.N().S(`) New() *`)
//line database_tpl.qtpl:307
		qw422016.E().S(typeName)
//line database_tpl.qtpl:307
		qw422016.N().S(`{
	return &`)
//line database_tpl.qtpl:308
		qw422016.E().S(typeName)
//line database_tpl.qtpl:308
		qw422016.N().S(`{}
}

// DecodeText implement pgtype.TextDecoder interface
func (dst *`)
//line database_tpl.qtpl:312
		qw422016.E().S(typeName)
//line database_tpl.qtpl:312
		qw422016.N().S(`) DecodeText(ci *pgtype.ConnInfo, src []byte) error {
	*dst = `)
//line database_tpl.qtpl:313
		qw422016.E().S(typeName)
//line database_tpl.qtpl:313
		qw422016.N().S(`{}
	if len(src) == 0 {
		return nil
	}
	`)
//line database_tpl.qtpl:317
		if t.Type == 'r' {
//line database_tpl.qtpl:317
			qw422016.N().S(`
	utr, err := pgtype.ParseUntypedTextRange(gotools.BytesToString(src))
	if err != nil {
		return err
	}
	`)
//line database_tpl.qtpl:322
		} else {
//line database_tpl.qtpl:322
			qw422016.N().S(`
	c := pgtype.NewCompositeTextScanner(ci, src)
`)
//line database_tpl.qtpl:324
		}
//line database_tpl.qtpl:324
		qw422016.N().S(`
`)
//line database_tpl.qtpl:326
		if t.Type == 'r' {
//line database_tpl.qtpl:326
			qw422016.N().S(`    	dst.LowerType = utr.LowerType
    	dst.UpperType = utr.UpperType

    	if dst.LowerType == pgtype.Empty {
    		return nil
    	}

    	if dst.LowerType == pgtype.Inclusive || dst.LowerType == pgtype.Exclusive {
    		if err := dst.Lower.DecodeText(ci, gotools.StringToBytes(utr.Lower)); err != nil {
    			return err
    		}
    	}

    	if dst.UpperType == pgtype.Inclusive || dst.UpperType == pgtype.Exclusive {
    		if err := dst.Upper.DecodeText(ci, gotools.StringToBytes(utr.Upper)); err != nil {
    			return err
    		}
    	}
`)
//line database_tpl.qtpl:345
		} else {
//line database_tpl.qtpl:346
			for _, attr := range t.Attr {
//line database_tpl.qtpl:346
				qw422016.N().S(`	`)
//line database_tpl.qtpl:347
				if strings.HasPrefix(attr.Type, "pgtype.") || strings.HasPrefix(attr.Name, "psql.") {
//line database_tpl.qtpl:347
					qw422016.N().S(`
	c.ScanDecoder`)
//line database_tpl.qtpl:348
				} else {
//line database_tpl.qtpl:348
					qw422016.N().S(`c.ScanValue`)
//line database_tpl.qtpl:348
				}
//line database_tpl.qtpl:348
				qw422016.N().S(`(&dst.`)
//line database_tpl.qtpl:348
				qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:348
				qw422016.N().S(`)
	if c.Err() != nil {
		return c.Err()
	}
`)
//line database_tpl.qtpl:352
			}
//line database_tpl.qtpl:353
		}
//line database_tpl.qtpl:353
		qw422016.N().S(`
	return nil
}

// DecodeBinary implement pgtype.BinaryDecoder interface
func (dst *`)
//line database_tpl.qtpl:359
		qw422016.E().S(typeName)
//line database_tpl.qtpl:359
		qw422016.N().S(`) DecodeBinary(ci *pgtype.ConnInfo, src []byte) error {
	*dst = `)
//line database_tpl.qtpl:360
		qw422016.E().S(typeName)
//line database_tpl.qtpl:360
		qw422016.N().S(`{}
	if len(src) == 0 {
		return nil
	}

`)
//line database_tpl.qtpl:365
		if t.Type == 'r' {
//line database_tpl.qtpl:365
			qw422016.N().S(`	utr, err := pgtype.ParseUntypedBinaryRange(src)
	if err != nil {
		return err
	}
`)
//line database_tpl.qtpl:370
		} else {
//line database_tpl.qtpl:370
			qw422016.N().S(`	c := pgtype.NewCompositeBinaryScanner(ci, src)
	countFields := c.FieldCount()
`)
//line database_tpl.qtpl:373
		}
//line database_tpl.qtpl:374
		if t.Type == 'r' {
//line database_tpl.qtpl:374
			qw422016.N().S(`    	dst.LowerType = utr.LowerType
    	dst.UpperType = utr.UpperType

    	if dst.LowerType == pgtype.Empty {
    		return nil
    	}

    	if dst.LowerType == pgtype.Inclusive || dst.LowerType == pgtype.Exclusive {
    		if err := dst.Lower.DecodeBinary(ci, utr.Lower); err != nil {
    			return err
    		}
    	}

    	if dst.UpperType == pgtype.Inclusive || dst.UpperType == pgtype.Exclusive {
    		if err := dst.Upper.DecodeBinary(ci, utr.Upper); err != nil {
    			return err
    		}
    	}
`)
//line database_tpl.qtpl:393
		} else {
//line database_tpl.qtpl:394
			for i, attr := range t.Attr {
//line database_tpl.qtpl:394
				qw422016.N().S(`	//	    rich end of elements
	if countFields < `)
//line database_tpl.qtpl:396
				qw422016.N().D(i + 1)
//line database_tpl.qtpl:396
				qw422016.N().S(` || !c.Next() {
		return nil
	}
	if err := `)
//line database_tpl.qtpl:399
				if strings.HasPrefix(attr.Name, "pgtype.") || strings.HasPrefix(attr.Name, "psql.") {
//line database_tpl.qtpl:399
					qw422016.N().S(`&dst.`)
//line database_tpl.qtpl:399
					qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:399
					qw422016.N().S(`.DecodeBinary(ci, c.Bytes())
`)
//line database_tpl.qtpl:400
				} else {
//line database_tpl.qtpl:400
					qw422016.N().S(`ci.Scan(c.OID(), pgtype.BinaryFormatCode, c.Bytes(), &dst.`)
//line database_tpl.qtpl:400
					qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:400
					qw422016.N().S(`)`)
//line database_tpl.qtpl:400
				}
//line database_tpl.qtpl:400
				qw422016.N().S(`; err != nil {
		logs.ErrorLog(err, "`)
//line database_tpl.qtpl:401
				qw422016.E().S(typeName)
//line database_tpl.qtpl:401
				qw422016.N().S(`.`)
//line database_tpl.qtpl:401
				qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:401
				qw422016.N().S(`")
		return err
	}
`)
//line database_tpl.qtpl:404
			}
//line database_tpl.qtpl:405
		}
//line database_tpl.qtpl:405
		qw422016.N().S(`
	return nil
}

// Scan implement sql.Scanner interface
func (dst *`)
//line database_tpl.qtpl:411
		qw422016.E().S(typeName)
//line database_tpl.qtpl:411
		qw422016.N().S(`) Scan(src any) error {
	switch src := src.(type) {
	case nil:
		*dst = `)
//line database_tpl.qtpl:414
		qw422016.E().S(typeName)
//line database_tpl.qtpl:414
		qw422016.N().S(`{}
		return nil
	case string:
		return dst.DecodeText(nil, gotools.StringToBytes(src))
	case []byte:
		return dst.DecodeText(nil, src)
	default:
		return fmt.Errorf("cannot scan %T", src)
	}
}
`)
//line database_tpl.qtpl:424
	}
//line database_tpl.qtpl:425
}

//line database_tpl.qtpl:425
func (c *PackageBuilder) WriteCreateTypeInterface(qq422016 qtio422016.Writer, t dbEngine.Types, typeName, name, typeCol string) {
//line database_tpl.qtpl:425
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:425
	c.StreamCreateTypeInterface(qw422016, t, typeName, name, typeCol)
//line database_tpl.qtpl:425
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:425
}

//line database_tpl.qtpl:425
func (c *PackageBuilder) CreateTypeInterface(t dbEngine.Types, typeName, name, typeCol string) string {
//line database_tpl.qtpl:425
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:425
	c.WriteCreateTypeInterface(qb422016, t, typeName, name, typeCol)
//line database_tpl.qtpl:425
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:425
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:425
	return qs422016
//line database_tpl.qtpl:425
}

// end CreateTypeInterface
//

//line database_tpl.qtpl:428
func StreamCreateTableConstructor(qw422016 *qt422016.Writer, goName, name string) {
//line database_tpl.qtpl:428
	qw422016.N().S(`// New`)
//line database_tpl.qtpl:429
	qw422016.E().S(goName)
//line database_tpl.qtpl:429
	qw422016.N().S(` create new instance of table `)
//line database_tpl.qtpl:429
	qw422016.E().S(goName)
//line database_tpl.qtpl:429
	qw422016.N().S(`
func (d *Database) New`)
//line database_tpl.qtpl:430
	qw422016.E().S(goName)
//line database_tpl.qtpl:430
	qw422016.N().S(`(ctx context.Context) (*`)
//line database_tpl.qtpl:430
	qw422016.E().S(goName)
//line database_tpl.qtpl:430
	qw422016.N().S(`, error) {
	switch table, err := New`)
//line database_tpl.qtpl:431
	qw422016.E().S(goName)
//line database_tpl.qtpl:431
	qw422016.N().S(`(d.DB); err.(type) {
	case nil:
		return table, nil

	// no found on Database - get data of table from Conn
	case dbEngine.ErrNotFoundTable:
		table, err := New`)
//line database_tpl.qtpl:437
	qw422016.E().S(goName)
//line database_tpl.qtpl:437
	qw422016.N().S(`FromConn(ctx, d.PsqlConn())
		if err != nil {
			return nil, err
		}
		d.Tables[table.Name()] = table
		return table, nil
		
	default:
		return nil, err
	}
}
`)
//line database_tpl.qtpl:448
}

//line database_tpl.qtpl:448
func WriteCreateTableConstructor(qq422016 qtio422016.Writer, goName, name string) {
//line database_tpl.qtpl:448
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:448
	StreamCreateTableConstructor(qw422016, goName, name)
//line database_tpl.qtpl:448
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:448
}

//line database_tpl.qtpl:448
func CreateTableConstructor(goName, name string) string {
//line database_tpl.qtpl:448
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:448
	WriteCreateTableConstructor(qb422016, goName, name)
//line database_tpl.qtpl:448
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:448
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:448
	return qs422016
//line database_tpl.qtpl:448
}
