// Code generated by qtc from "table.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:1
package tpl

//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:2
import (
	"fmt"
	"github.com/iancoleman/strcase"
	"strings"
)

// table structures generator

//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:9
type Table struct {
	name    string
	dbName  string
	columns []string
	comment string
	imports []string
	typ     string
}

func NewTable(name, dbName, comment, typ string, columns, imports []string) *Table {
	return &Table{
		name:    name,
		dbName:  dbName,
		columns: columns,
		comment: comment,
		imports: imports,
		typ:     typ,
	}
}

//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:29
func (t *Table) StreamTable(qw422016 *qt422016.Writer, title string) {
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:29
	qw422016.N().S(`
`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:30
	StreamHeader(qw422016, t.imports, title)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:30
	qw422016.N().S(`
// %s implement operations for `)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:31
	qw422016.E().S(t.typ)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:31
	qw422016.N().S(`
// DB comment: '`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:32
	qw422016.E().S(t.comment)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:32
	qw422016.N().S(`'
type `)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:33
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:33
	qw422016.N().S(` struct {
	*psql.Table
	Record 				*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:35
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:35
	qw422016.N().S(`Fields
	DoCopyPoll      	[]*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:36
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:36
	qw422016.N().S(`Fields

	chErr               *chan error
	doCopyPoolCount 	int
	doCopyPoolColumns 	[]string
	doCopyValuesCount 	int
	doCopyErr       	error
	lock       			sync.RWMutex
	ticket	 			*time.Ticker
	poolDuration 	    time.Duration
}

// New`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:48
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:48
	qw422016.N().S(` create new instance of table object
func New`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:49
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:49
	qw422016.N().S(`(DB *dbEngine.DB) (*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:49
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:49
	qw422016.N().S(`, error) {
	table, ok := DB.Tables["`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:50
	qw422016.E().S(t.dbName)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:50
	qw422016.N().S(`"]
    if !ok {
      return nil, dbEngine.ErrNotFoundTable{Table: "`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:52
	qw422016.E().S(t.dbName)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:52
	qw422016.N().S(`"}
    }

    return &`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:55
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:55
	qw422016.N().S(`{
		Table: table.(*psql.Table),
    }, nil
}
// New`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:59
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:59
	qw422016.N().S(` create new instance of table object from Connection
// it's necessary if Database create without reading schema of DB
func New`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:61
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:61
	qw422016.N().S(`FromConn(ctx context.Context, conn *psql.Conn) (*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:61
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:61
	qw422016.N().S(`, error) {
	t, err := conn.NewTableWithCheck(ctx, "`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:62
	qw422016.E().S(t.dbName)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:62
	qw422016.N().S(`")
	if err != nil {
		logs.ErrorLog(err, "during NewTableWithCheck")
		return nil, err
	}

    return &`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:68
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:68
	qw422016.N().S(`{
		Table: t,
    }, nil
}
// implementation pgx.CopyFromSource
// CopyFromSource is the interface used by *Conn.CopyFrom as the source for copy data.

// Next returns true if there is another row and makes the next row data
// available to Values(). When there are no more rows available or an error
// has occurred it returns false.
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:78
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:78
	qw422016.N().S(`) Next() bool {
	t.doCopyValuesCount++
	return t.doCopyValuesCount < len(t.DoCopyPoll)
}
// Values returns the values for the current row.
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:83
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:83
	qw422016.N().S(`) Values() ([]any, error) {
	return slices.Collect(func(yield func(any) bool) {
		for i, col := range t.doCopyPoolColumns {
			if !yield( t.DoCopyPoll[t.doCopyValuesCount].ColValue(col) ) {
				return
			}
		}
	}), nil
}
// Err returns any error that has been encountered by the CopyFromSource. If
// this is not nil *Conn.CopyFrom will abort the copy.
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:94
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:94
	qw422016.N().S(`) Err() error {
	return t.doCopyErr
}
// InitPoolCopy init environments for CopyFrom operation
// capOfPool define max pool capacity
// d - interval for flash
// columns - names of columns for CopyFrom (all columns of table if it not present)
// chErr - channel for error when CopyFrom return it
// on this case operation will terminated
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:103
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:103
	qw422016.N().S(`) InitPoolCopy(ctx context.Context, capOfPool int, chErr *chan error, d time.Duration, columns ...string) {
	t.lock.Lock()
	defer t.lock.Unlock()

	t.DoCopyPoll = make([]*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:107
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:107
	qw422016.N().S(`Fields, 0, capOfPool)
	t.doCopyPoolCount = 0
	if len(columns) > 0 {
		t.doCopyPoolColumns = columns
	} else {
		t.doCopyPoolColumns = make([]string, len(t.Columns()))
		for i, col := range t.Columns() {
			t.doCopyPoolColumns[i] = col.Name()
		}
	}
	t.chErr = chErr
	t.ticket = time.NewTicker(d)
	t.doCopyErr = nil
	t.poolDuration = d

	// run DoCopy every 'd' ms
	go func() {
		defer t.ticket.Stop()
		for {
			select {
			case <-t.ticket.C:
				err := t.doCopy(ctx)
				if err != nil {
					return
				}
			case <-ctx.Done():
				return
			}
		}
	}()
}
// AddToPoolCopy add 'record' into copy pool
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:139
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:139
	qw422016.N().S(`) AddToPoolCopy(ctx context.Context, record ... *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:139
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:139
	qw422016.N().S(`Fields) error {
	if t.doCopyErr != nil {
		return t.doCopyErr
	}

	if cap(t.DoCopyPoll) == 0 {
		t.InitPoolCopy(ctx, 3, nil,  100 * time.Millisecond)
	}

	t.lock.Lock()
	t.DoCopyPoll = append(t.DoCopyPoll, record... )
	t.doCopyPoolCount++
	t.lock.Unlock()

	if t.doCopyPoolCount == cap(t.DoCopyPoll) {
		err := t.doCopy(ctx)
		if err != nil {
			t.ticket.Stop()
			return err
		}
		t.ticket.Reset(t.poolDuration)
	}

	return nil
}
// FlashPoolAndReset inserted all record from Poll as is
// returns slice of records which were be not inserted
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:166
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:166
	qw422016.N().S(`) FlashPoolAndReset(ctx context.Context) ([]*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:166
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:166
	qw422016.N().S(`Fields, error) {
	t.ticket.Reset(t.poolDuration)
	err := t.doCopy(ctx)
	if err != nil {
		t.ticket.Stop()
		if m, ok := dbEngine.IsErrorDuplicated(err); ok {
			logs.ErrorLog(err, m)
			return t.InsertPoolAndReset(ctx), err
		}
		return nil, err
	}

	return nil, nil
}
// InsertPoolAndReset inserted all record from Poll as is
// returns slice of records which were be not inserted
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:182
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:182
	qw422016.N().S(`) InsertPoolAndReset(ctx context.Context) []*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:182
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:182
	qw422016.N().S(`Fields {
	t.lock.Lock()
	defer t.lock.Unlock()

	columns := t.doCopyPoolColumns
	failRecords := make([]*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:187
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:187
	qw422016.N().S(`Fields,0)
	allInserted := int64(0)

	for _, record := range t.DoCopyPoll {
		v := make([]any, len(columns))
		for i, name := range columns {
			v[i] = record.RefColValue(name)
		}
		i, err := t.Insert(ctx,
			dbEngine.Columns(columns...),
			dbEngine.Values(v...),
		)
		if err != nil {
			failRecords = append(failRecords, record)
			continue
		}
		allInserted += i
	}

	t.DoCopyPoll = t.DoCopyPoll[:0]
	t.doCopyPoolCount = 0
	logs.DebugLog("%%d record inserted by InsertPoolAndReset", allInserted)

	return failRecords
}
// `)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:212
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:212
	qw422016.N().S(`Fields data object for '`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:212
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:212
	qw422016.N().S(`' columns
type `)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:213
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:213
	qw422016.N().S(`Fields struct {
	// columns of table %s
`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:215
	for _, name := range t.columns {
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:215
		qw422016.N().S(`
	`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:216
		qw422016.E().S(fmt.Sprintf(colFormat, strcase.ToCamel(name), "typeCol", strings.ToLower(name)))
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:216
		qw422016.N().S(`
    `)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:217
	}
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:217
	qw422016.N().S(`
}
// New%sFields create new instance & fill struct fill for avoid panic
func New`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:220
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:220
	qw422016.N().S(`Fields() *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:220
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:220
	qw422016.N().S(`Fields{
	return &`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:221
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:221
	qw422016.N().S(`Fields{
		// init properties `)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:222
	qw422016.E().S(t.typ)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:222
	qw422016.N().S(` initValues
	}
}
// RefColValue return referral of column
func (r *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:226
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:226
	qw422016.N().S(`Fields) RefColValue(name string) any{
	switch name {
`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:228
	for _, name := range t.columns {
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:228
		qw422016.N().S(`
		case "`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:229
		qw422016.E().S(name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:229
		qw422016.N().S(`":
    		return &r.`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:230
		qw422016.E().S(strcase.ToCamel(name))
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:230
		qw422016.N().S(`
    `)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:231
	}
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:231
	qw422016.N().S(`
   	default:
		return nil
	}
}
// ColValue return value of column
func (r *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:237
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:237
	qw422016.N().S(`Fields) ColValue(name string) any{
	switch name {
`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:239
	for _, name := range t.columns {
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:239
		qw422016.N().S(`		case "`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:240
		qw422016.E().S(name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:240
		qw422016.N().S(`":
    		return r.`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:241
		qw422016.E().S(strcase.ToCamel(name))
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:241
		qw422016.N().S(`
    `)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:242
	}
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:242
	qw422016.N().S(`
   	default:
		return nil
	}
}
// GetFields implement dbEngine.RowScanner interface
func (r *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:248
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:248
	qw422016.N().S(`Fields) GetFields(columns []dbEngine.Column) []any {
	v := make([]any, len(columns))
	for i, col := range columns {
		v[i] = r.RefColValue( col.Name() )
	}

	return v
}
// GetValue implement httpgo.RouteDTO interface
func (r *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:257
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:257
	qw422016.N().S(`Fields) GetValue() any {
	return r
}
// NewValue implement httpgo.RouteDTO interface
func (r *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:261
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:261
	qw422016.N().S(`Fields) NewValue() any {
	return New`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:262
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:262
	qw422016.N().S(`Fields()
}
// NewRecord return new row of table
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:265
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:265
	qw422016.N().S(`) NewRecord() *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:265
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:265
	qw422016.N().S(`Fields{
   t.Record = New`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:266
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:266
	qw422016.N().S(`Fields()
	return t.Record
}
// GetFields implement dbEngine.RowScanner interface
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:270
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:270
	qw422016.N().S(`) GetFields(columns []dbEngine.Column) []any {
	if len(columns) == 0 {
		columns = t.Columns()
	}

	return t.NewRecord().GetFields(columns)
}
// SelectSelfScanEach exec request to DB & populate record & call each for each row of query
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:278
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:278
	qw422016.N().S(`) SelectSelfScanEach(ctx context.Context, each func(record *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:278
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:278
	qw422016.N().S(`Fields) error, Options ...dbEngine.BuildSqlOptions) error {
	return t.SelectAndScanEach(ctx,
			func() error {
			 	if each != nil {
					return each(t.Record)
				}

				 return nil
			}, t, Options ... )
}
// SelectAll run sql according to Options & return slice of record
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:289
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:289
	qw422016.N().S(`) SelectAll(ctx context.Context, Options ...dbEngine.BuildSqlOptions) (res []*`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:289
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:289
	qw422016.N().S(`Fields, err error) {
	err = t.SelectAndScanEach(ctx,
			func() error {
			 	res = append(res, t.Record)
				return nil
			}, t, Options ... )
	if err != nil {
		logs.ErrorLog(err, "during doCopy")
		return nil, err
	}

	return res, nil
}
// Insert new record into table
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:303
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:303
	qw422016.N().S(`) Insert(ctx context.Context, Options ...dbEngine.BuildSqlOptions) (int64, error) {
	if len(Options) == 0 {
		v := make([]any, 0, len(t.Columns()))
		columns := make([]string, 0, len(t.Columns()))
		for _, col := range t.Columns() {
			if col.AutoIncrement() {
				continue
			}

			columns = append(columns, col.Name())
			v = append(v, t.Record.ColValue( col.Name() ) )
		}
		Options = append(
			Options,
			dbEngine.Columns(columns...),
			dbEngine.Values(v... ),
		)
   }

	return t.Table.Insert(ctx, Options...)
}
// Update record of table according to Options
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:325
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:325
	qw422016.N().S(`) Update(ctx context.Context, Options ...dbEngine.BuildSqlOptions) (int64, error) {
	if len(Options) == 0 {
		v := make([]any, 0, len(t.Columns()))
		priV := make([]any, 0)
		columns := make([]string, 0, len(t.Columns()))
		priColumns := make([]string, 0, len(t.Columns()))
		for _, col := range t.Columns() {
			if col.Primary() {
				priColumns = append( priColumns, col.Name() )
				priV = append(priV, t.Record.ColValue( col.Name() ))
				continue
			}

			columns = append( columns, col.Name() )
			v = append(v, t.Record.ColValue( col.Name() ) )
		}

		Options = append(
			Options,
			dbEngine.Columns(columns...),
			dbEngine.WhereForSelect(priColumns...),
			dbEngine.Values(append(v, priV...)... ),
		)
	}

	return t.Table.Update(ctx, Options...)
}

// Upsert insert new Record into table according to Options or update if this record exists
func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:354
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:354
	qw422016.N().S(`) Upsert(ctx context.Context, Options ...dbEngine.BuildSqlOptions) (int64, error) {
	if len(Options) == 0 {
		v := make([]any, 0, len(t.Columns()))
		priV := make([]any, 0)
		columns := make([]string, 0, len(t.Columns()))
		priColumns := make([]string, 0, len(t.Columns()))
		for _, col := range t.Columns() {
			if col.Primary() {
				priColumns = append( priColumns, col.Name() )
				priV = append(priV, t.Record.ColValue( col.Name() ))
			}

			if col.AutoIncrement() {
				continue
			}

			columns = append( columns, col.Name() )
			v = append(v, t.Record.ColValue( col.Name() ) )
		}

		Options = append(
			Options,
			dbEngine.Columns(columns...),
			dbEngine.WhereForSelect(priColumns...),
			dbEngine.Values(v... ),
		)
	}

	return t.Table.Upsert(ctx, Options...)
}

func (t *`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:385
	qw422016.E().S(t.name)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:385
	qw422016.N().S(`) doCopy(ctx context.Context) error {
	if len(t.DoCopyPoll) == 0 {
		return nil
	}

	t.lock.Lock()
	defer t.lock.Unlock()

	t.doCopyValuesCount = -1
	i, err := t.DoCopy(ctx, t, t.doCopyPoolColumns...)
	if err != nil {
		t.doCopyErr = err
		if t.chErr != nil {
		   *t.chErr <- err
		} else {
			logs.ErrorLog(err, "during doCopy")
		}

		return err
	}

	t.DoCopyPoll = t.DoCopyPoll[:0]
	t.doCopyPoolCount = 0
	logs.DebugLog("record insert with CopyFrom: %d from %d ", i, t.doCopyValuesCount)

	return nil
}
`)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
}

//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
func (t *Table) WriteTable(qq422016 qtio422016.Writer, title string) {
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
	t.StreamTable(qw422016, title)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
	qt422016.ReleaseWriter(qw422016)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
}

//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
func (t *Table) Table(title string) string {
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
	qb422016 := qt422016.AcquireByteBuffer()
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
	t.WriteTable(qb422016, title)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
	qs422016 := string(qb422016.B)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
	qt422016.ReleaseByteBuffer(qb422016)
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
	return qs422016
//line /Users/ruslan_bik/GolandProjects/dbEngine/generators/go/tpl/table.qtpl:412
}
