// Code generated by qtc from "database_tpl.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line database_tpl.qtpl:1
package _go

//line database_tpl.qtpl:2
import (
	"fmt"

	"github.com/iancoleman/strcase"
	"github.com/ruslanBik4/dbEngine/dbEngine"
	"github.com/ruslanBik4/dbEngine/dbEngine/psql"
)

//line database_tpl.qtpl:11
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line database_tpl.qtpl:11
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line database_tpl.qtpl:11
func (c *Creator) StreamCreateDatabase(qw422016 *qt422016.Writer, listRoutines []string) {
//line database_tpl.qtpl:11
	qw422016.N().S(`
// Code generated by dbEngine-gen-go. DO NOT EDIT!
// versions:
// 	dbEngine v1.1.6
// source: %s %s

package db

import (
	"fmt"
	"time"
	"strings"
`)
//line database_tpl.qtpl:23
	for _, lib := range c.packages {
//line database_tpl.qtpl:23
		qw422016.N().S(`"`)
//line database_tpl.qtpl:23
		qw422016.E().S(lib)
//line database_tpl.qtpl:23
		qw422016.N().S(`"
`)
//line database_tpl.qtpl:24
	}
//line database_tpl.qtpl:24
	qw422016.N().S(`
	"github.com/jackc/pgconn"

	"github.com/ruslanBik4/logs"
	"github.com/ruslanBik4/dbEngine/dbEngine"
    "github.com/ruslanBik4/dbEngine/dbEngine/psql"

	"golang.org/x/net/context"
	"github.com/pkg/errors"
)
`)
//line database_tpl.qtpl:35
	for name, typ := range c.db.Types {
//line database_tpl.qtpl:35
		c.StreamCreateTypeInterface(qw422016, typ, strcase.ToCamel(name), name, c.Types[name])
//line database_tpl.qtpl:35
	}
//line database_tpl.qtpl:35
	qw422016.N().S(`
// Database is root interface for operation for %s.%s
type Database struct {
	*dbEngine.DB
	CreateAt time.Time
}
// NewDatabase create new Database with minimal necessary handlers
func NewDatabase(ctx context.Context, noticeHandler pgconn.NoticeHandler, channelHandler pgconn.NotificationHandler, channels ...string) (*Database, error) {
	if noticeHandler == nil {
		noticeHandler = printNotice
	}
	conn := psql.NewConn(nil, nil, noticeHandler, channels...)
	if channelHandler != nil {
		conn.ChannelHandler = channelHandler
	}

	DB, err := dbEngine.NewDB(ctx, conn)
	if err != nil {
		logs.ErrorLog(err, "")
		return nil, err
	}

	return &Database{DB, time.Now()}, nil
}
// PsqlConn return connection as *psql.Conn
// need for some low-level operation,
// invoke Conn.Select...(custom sql),
//        New{table_name}FromConn, etc.
func (d *Database) PsqlConn() *psql.Conn {
	return (d.Conn).(*psql.Conn)
}
`)
//line database_tpl.qtpl:67
	for name := range c.db.Tables {
//line database_tpl.qtpl:67
		c.StreamCreateTableConstructor(qw422016, strcase.ToCamel(name), name)
//line database_tpl.qtpl:67
	}
//line database_tpl.qtpl:68
	for _, name := range listRoutines {
//line database_tpl.qtpl:68
		c.StreamCreateRoutinesInvoker(qw422016, c.db.Routines[name].(*psql.Routine), name)
//line database_tpl.qtpl:68
	}
//line database_tpl.qtpl:68
	qw422016.N().S(`// printNotice logging some psql messages (invoked command 'RAISE ...')
func printNotice(c *pgconn.PgConn, n *pgconn.Notice) {

	switch {
    case n.Code == "42P07" || strings.Contains(n.Message, "skipping") :
		logs.DebugLog("skip operation: %%s", n.Message)

	case n.Severity == "INFO" :
		logs.StatusLog(n.Message)

	case n.Code > "00000" :
		err := (*pgconn.PgError)(n)
		logs.CustomLog(logs.CRITICAL, "DB_EXEC",  err.File, int(err.Line),
			fmt.Sprintf("%v, hint: %s, where: %s, %s %s", err, n.Hint, n.Where,  err.SQLState(), err.Routine), logs.FgErr)

	case strings.HasPrefix(n.Message, "[[ERROR]]") :
		logs.ErrorLog(errors.New(strings.TrimPrefix(n.Message, "[[ERROR]]") + n.Severity))

	default: // DEBUG
		logs.DebugLog("%+v %s (PID:%d)", n.Severity, n.Message, c.PID())
	}
}
`)
//line database_tpl.qtpl:91
}

//line database_tpl.qtpl:91
func (c *Creator) WriteCreateDatabase(qq422016 qtio422016.Writer, listRoutines []string) {
//line database_tpl.qtpl:91
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:91
	c.StreamCreateDatabase(qw422016, listRoutines)
//line database_tpl.qtpl:91
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:91
}

//line database_tpl.qtpl:91
func (c *Creator) CreateDatabase(listRoutines []string) string {
//line database_tpl.qtpl:91
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:91
	c.WriteCreateDatabase(qb422016, listRoutines)
//line database_tpl.qtpl:91
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:91
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:91
	return qs422016
//line database_tpl.qtpl:91
}

//line database_tpl.qtpl:93
func (c *Creator) StreamCreateTypeInterface(qw422016 *qt422016.Writer, t dbEngine.Types, typeName, name, typeCol string) {
//line database_tpl.qtpl:94
	if len(t.Enumerates) > 0 {
//line database_tpl.qtpl:95
	} else {
//line database_tpl.qtpl:95
		qw422016.N().S(`// `)
//line database_tpl.qtpl:96
		qw422016.E().S(typeName)
//line database_tpl.qtpl:96
		qw422016.N().S(` create new instance of type `)
//line database_tpl.qtpl:96
		qw422016.E().S(name)
//line database_tpl.qtpl:96
		qw422016.N().S(`
type `)
//line database_tpl.qtpl:97
		qw422016.E().S(typeName)
//line database_tpl.qtpl:97
		qw422016.N().S(` struct {
`)
//line database_tpl.qtpl:98
		for _, tAttr := range t.Attr {
//line database_tpl.qtpl:98
			qw422016.N().S(`	`)
//line database_tpl.qtpl:99
			qw422016.N().S(fmt.Sprintf("%-21s\t%-13s\t", strcase.ToCamel(tAttr.Name), tAttr.Type))
//line database_tpl.qtpl:99
			qw422016.N().S(` `)
//line database_tpl.qtpl:99
			qw422016.N().S("`")
//line database_tpl.qtpl:99
			qw422016.N().S(`json:"`)
//line database_tpl.qtpl:99
			qw422016.E().S(tAttr.Name)
//line database_tpl.qtpl:99
			qw422016.N().S(`"`)
//line database_tpl.qtpl:99
			qw422016.N().S("`")
//line database_tpl.qtpl:99
			qw422016.N().S(`
`)
//line database_tpl.qtpl:100
		}
//line database_tpl.qtpl:100
		qw422016.N().S(`}
// DecodeText implement pgtype.TextDecoder interface
func (dst *`)
//line database_tpl.qtpl:103
		qw422016.E().S(typeName)
//line database_tpl.qtpl:103
		qw422016.N().S(`) DecodeText(ci *pgtype.ConnInfo, src []byte) error {
	if len(src) == 0 {
		*dst = `)
//line database_tpl.qtpl:105
		qw422016.E().S(typeName)
//line database_tpl.qtpl:105
		qw422016.N().S(`{}
		return nil
	}
	srcPart := bytes.Split(src[1:len(src)-1], []byte(","))
    *dst = `)
//line database_tpl.qtpl:109
		qw422016.E().S(typeName)
//line database_tpl.qtpl:109
		qw422016.N().S(`{
`)
//line database_tpl.qtpl:110
		for i, tAttr := range t.Attr {
//line database_tpl.qtpl:110
			qw422016.N().S(`		`)
//line database_tpl.qtpl:111
			qw422016.N().S(c.GetFuncForDecode(&tAttr, i))
//line database_tpl.qtpl:111
			qw422016.N().S(`,
`)
//line database_tpl.qtpl:112
		}
//line database_tpl.qtpl:112
		qw422016.N().S(`	}

	return nil
}
`)
//line database_tpl.qtpl:117
	}
//line database_tpl.qtpl:118
}

//line database_tpl.qtpl:118
func (c *Creator) WriteCreateTypeInterface(qq422016 qtio422016.Writer, t dbEngine.Types, typeName, name, typeCol string) {
//line database_tpl.qtpl:118
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:118
	c.StreamCreateTypeInterface(qw422016, t, typeName, name, typeCol)
//line database_tpl.qtpl:118
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:118
}

//line database_tpl.qtpl:118
func (c *Creator) CreateTypeInterface(t dbEngine.Types, typeName, name, typeCol string) string {
//line database_tpl.qtpl:118
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:118
	c.WriteCreateTypeInterface(qb422016, t, typeName, name, typeCol)
//line database_tpl.qtpl:118
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:118
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:118
	return qs422016
//line database_tpl.qtpl:118
}

//line database_tpl.qtpl:120
func (c *Creator) StreamCreateRoutinesInvoker(qw422016 *qt422016.Writer, r *psql.Routine, name string) {
//line database_tpl.qtpl:122
	camelName := strcase.ToCamel(name)
	args := make([]any, len(r.Params()))
	sql, _, _ := r.BuildSql(dbEngine.ArgsForSelect(args...))
	typeReturn := ""

//line database_tpl.qtpl:127
	if r.Type == psql.ROUTINE_TYPE_PROC {
//line database_tpl.qtpl:127
		qw422016.N().S(`// `)
//line database_tpl.qtpl:128
		qw422016.E().S(camelName)
//line database_tpl.qtpl:128
		qw422016.N().S(` call procedure '`)
//line database_tpl.qtpl:128
		qw422016.E().S(name)
//line database_tpl.qtpl:128
		qw422016.N().S(`'
// DB comment: '`)
//line database_tpl.qtpl:129
		qw422016.E().S(r.Comment)
//line database_tpl.qtpl:129
		qw422016.N().S(`'
func (d *Database) `)
//line database_tpl.qtpl:130
		qw422016.E().S(camelName)
//line database_tpl.qtpl:130
		qw422016.N().S(`(ctx context.Context,
				`)
//line database_tpl.qtpl:131
		c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:131
		qw422016.N().S(`
) error {
	return d.Conn.ExecDDL(ctx,
				`)
//line database_tpl.qtpl:131
		qw422016.N().S("`")
//line database_tpl.qtpl:134
		qw422016.E().S(sql)
//line database_tpl.qtpl:134
		qw422016.N().S(``)
//line database_tpl.qtpl:134
		qw422016.N().S("`")
//line database_tpl.qtpl:134
		qw422016.N().S(`,
				`)
//line database_tpl.qtpl:135
		c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:135
		qw422016.N().S(`
			)
}
`)
//line database_tpl.qtpl:138
	} else {
//line database_tpl.qtpl:139
		switch len(r.Columns()) {
//line database_tpl.qtpl:140
		case 0:
//line database_tpl.qtpl:141
			typeReturn = c.udtToReturnType(r.UdtName)

//line database_tpl.qtpl:142
		case 1:
//line database_tpl.qtpl:144
			param := r.Columns()[0]
			typeReturn, _ = c.chkTypes(param, strcase.ToCamel(param.Name()))

//line database_tpl.qtpl:147
		default:
//line database_tpl.qtpl:148
			typeReturn = fmt.Sprintf("*%sRowScanner", camelName)

//line database_tpl.qtpl:149
			c.StreamCreateRowScanner(qw422016, r, camelName)
//line database_tpl.qtpl:149
			qw422016.N().S(`
`)
//line database_tpl.qtpl:150
		}
//line database_tpl.qtpl:150
		qw422016.N().S(`// `)
//line database_tpl.qtpl:151
		qw422016.E().S(camelName)
//line database_tpl.qtpl:151
		qw422016.N().S(` run query with select DB function '`)
//line database_tpl.qtpl:151
		qw422016.E().S(name)
//line database_tpl.qtpl:151
		qw422016.N().S(`: `)
//line database_tpl.qtpl:151
		qw422016.E().S(r.UdtName)
//line database_tpl.qtpl:151
		qw422016.N().S(`'
// DB comment: '`)
//line database_tpl.qtpl:152
		qw422016.E().S(r.Comment)
//line database_tpl.qtpl:152
		qw422016.N().S(`'
// ATTENTION! It returns only 1 row `)
//line database_tpl.qtpl:153
		qw422016.E().S(typeReturn)
//line database_tpl.qtpl:153
		qw422016.N().S(`
func (d *Database) `)
//line database_tpl.qtpl:154
		qw422016.E().S(camelName)
//line database_tpl.qtpl:154
		qw422016.N().S(`(ctx context.Context,
				`)
//line database_tpl.qtpl:155
		c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:155
		qw422016.N().S(`
) (res `)
//line database_tpl.qtpl:156
		qw422016.E().S(typeReturn)
//line database_tpl.qtpl:156
		qw422016.N().S(`, err error) {
	err = d.Conn.SelectOneAndScan(ctx,
				&res,
				`)
//line database_tpl.qtpl:156
		qw422016.N().S("`")
//line database_tpl.qtpl:159
		qw422016.E().S(sql)
//line database_tpl.qtpl:159
		qw422016.N().S(`
				FETCH FIRST 1 ROW ONLY`)
//line database_tpl.qtpl:159
		qw422016.N().S("`")
//line database_tpl.qtpl:159
		qw422016.N().S(`,
				`)
//line database_tpl.qtpl:161
		c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:161
		qw422016.N().S(`
			)

	return
}
`)
//line database_tpl.qtpl:166
		if r.ReturnType() == "record" {
//line database_tpl.qtpl:167
			typeReturn = fmt.Sprintf("%sRowScanner", camelName)

//line database_tpl.qtpl:167
			qw422016.N().S(`// `)
//line database_tpl.qtpl:168
			qw422016.E().S(camelName)
//line database_tpl.qtpl:168
			qw422016.N().S(`Each run query with select DB function '`)
//line database_tpl.qtpl:168
			qw422016.E().S(name)
//line database_tpl.qtpl:168
			qw422016.N().S(`'
// DB comment: '`)
//line database_tpl.qtpl:169
			qw422016.E().S(r.Comment)
//line database_tpl.qtpl:169
			qw422016.N().S(`'
// each will get every row from &`)
//line database_tpl.qtpl:170
			qw422016.E().S(camelName)
//line database_tpl.qtpl:170
			qw422016.N().S(`sRowScanner
func (d *Database) `)
//line database_tpl.qtpl:171
			qw422016.E().S(camelName)
//line database_tpl.qtpl:171
			qw422016.N().S(`Each(ctx context.Context,
	each func(record *`)
//line database_tpl.qtpl:172
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:172
			qw422016.N().S(`) error,
	`)
//line database_tpl.qtpl:173
			c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:173
			qw422016.N().S(`
) error {
	res := &`)
//line database_tpl.qtpl:175
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:175
			qw422016.N().S(`{}
	err := d.Conn.SelectAndScanEach(ctx,
				func () error {
					defer func () {
					//	create new record
						*res = `)
//line database_tpl.qtpl:180
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:180
			qw422016.N().S(`{}
					}()

					if each != nil {
						return each(res)
					}
					return nil
				},
				res,
				`)
//line database_tpl.qtpl:180
			qw422016.N().S("`")
//line database_tpl.qtpl:189
			qw422016.E().S(sql)
//line database_tpl.qtpl:189
			qw422016.N().S(``)
//line database_tpl.qtpl:189
			qw422016.N().S("`")
//line database_tpl.qtpl:189
			qw422016.N().S(`,
				`)
//line database_tpl.qtpl:190
			c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:190
			qw422016.N().S(`
		)
	return err
}
// `)
//line database_tpl.qtpl:194
			qw422016.E().S(camelName)
//line database_tpl.qtpl:194
			qw422016.N().S(`All run query with select DB function '`)
//line database_tpl.qtpl:194
			qw422016.E().S(name)
//line database_tpl.qtpl:194
			qw422016.N().S(`'
// DB comment: '`)
//line database_tpl.qtpl:195
			qw422016.E().S(r.Comment)
//line database_tpl.qtpl:195
			qw422016.N().S(`'
// each will get every row from &`)
//line database_tpl.qtpl:196
			qw422016.E().S(camelName)
//line database_tpl.qtpl:196
			qw422016.N().S(`sRowScanner
func (d *Database) `)
//line database_tpl.qtpl:197
			qw422016.E().S(camelName)
//line database_tpl.qtpl:197
			qw422016.N().S(`All(ctx context.Context,
	`)
//line database_tpl.qtpl:198
			c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:198
			qw422016.N().S(`
) (res []`)
//line database_tpl.qtpl:199
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:199
			qw422016.N().S(`, err error) {
	buf := `)
//line database_tpl.qtpl:200
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:200
			qw422016.N().S(`{}
	err := d.Conn.SelectAndScanEach(ctx,
				func () error {
					res = append(res, buf)
					//	create new record
					buf = `)
//line database_tpl.qtpl:205
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:205
			qw422016.N().S(`{}

					return nil
				},
				&buf,
				`)
//line database_tpl.qtpl:205
			qw422016.N().S("`")
//line database_tpl.qtpl:210
			qw422016.E().S(sql)
//line database_tpl.qtpl:210
			qw422016.N().S(``)
//line database_tpl.qtpl:210
			qw422016.N().S("`")
//line database_tpl.qtpl:210
			qw422016.N().S(`,
				`)
//line database_tpl.qtpl:211
			c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:211
			qw422016.N().S(`
		)
	return err
}
`)
//line database_tpl.qtpl:215
		}
//line database_tpl.qtpl:215
		qw422016.N().S(`

`)
//line database_tpl.qtpl:217
	}
//line database_tpl.qtpl:217
	qw422016.N().S(`
`)
//line database_tpl.qtpl:218
}

//line database_tpl.qtpl:218
func (c *Creator) WriteCreateRoutinesInvoker(qq422016 qtio422016.Writer, r *psql.Routine, name string) {
//line database_tpl.qtpl:218
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:218
	c.StreamCreateRoutinesInvoker(qw422016, r, name)
//line database_tpl.qtpl:218
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:218
}

//line database_tpl.qtpl:218
func (c *Creator) CreateRoutinesInvoker(r *psql.Routine, name string) string {
//line database_tpl.qtpl:218
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:218
	c.WriteCreateRoutinesInvoker(qb422016, r, name)
//line database_tpl.qtpl:218
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:218
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:218
	return qs422016
//line database_tpl.qtpl:218
}

//line database_tpl.qtpl:220
func (c *Creator) StreamCreateRowScanner(qw422016 *qt422016.Writer, r *psql.Routine, camelName string) {
//line database_tpl.qtpl:220
	qw422016.N().S(`// `)
//line database_tpl.qtpl:221
	qw422016.E().S(camelName)
//line database_tpl.qtpl:221
	qw422016.N().S(`RowScanner run query with select
type `)
//line database_tpl.qtpl:222
	qw422016.E().S(camelName)
//line database_tpl.qtpl:222
	qw422016.N().S(`RowScanner struct {
`)
//line database_tpl.qtpl:223
	for _, param := range r.Columns() {
//line database_tpl.qtpl:225
		s := strcase.ToCamel(param.Name())
		typeCol, _ := c.chkTypes(param, s)

//line database_tpl.qtpl:227
		qw422016.N().S(`	`)
//line database_tpl.qtpl:228
		qw422016.E().S(s)
//line database_tpl.qtpl:228
		qw422016.N().S(`    `)
//line database_tpl.qtpl:228
		qw422016.E().S(typeCol)
//line database_tpl.qtpl:228
		qw422016.N().S(`  `)
//line database_tpl.qtpl:228
		qw422016.N().S("`")
//line database_tpl.qtpl:228
		qw422016.N().S(`json:"`)
//line database_tpl.qtpl:228
		qw422016.E().S(param.Name())
//line database_tpl.qtpl:228
		qw422016.N().S(`"`)
//line database_tpl.qtpl:228
		qw422016.N().S("`")
//line database_tpl.qtpl:228
		qw422016.N().S(`
`)
//line database_tpl.qtpl:229
	}
//line database_tpl.qtpl:229
	qw422016.N().S(`}
// GetFields implement dbEngine.RowScanner interface
func (r *`)
//line database_tpl.qtpl:232
	qw422016.E().S(camelName)
//line database_tpl.qtpl:232
	qw422016.N().S(`RowScanner) GetFields(columns []dbEngine.Column) []any {
	v := make([]any, len(columns))
	for i, col := range columns {
		switch col.Name() {
`)
//line database_tpl.qtpl:236
	for _, param := range r.Columns() {
//line database_tpl.qtpl:236
		qw422016.N().S(`		case "`)
//line database_tpl.qtpl:237
		qw422016.E().S(param.Name())
//line database_tpl.qtpl:237
		qw422016.N().S(`":
			v[i] =  &r.`)
//line database_tpl.qtpl:238
		qw422016.N().S(strcase.ToCamel(param.Name()))
//line database_tpl.qtpl:238
		qw422016.N().S(`
`)
//line database_tpl.qtpl:239
	}
//line database_tpl.qtpl:239
	qw422016.N().S(`		}
	}

	return v
}
`)
//line database_tpl.qtpl:245
}

//line database_tpl.qtpl:245
func (c *Creator) WriteCreateRowScanner(qq422016 qtio422016.Writer, r *psql.Routine, camelName string) {
//line database_tpl.qtpl:245
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:245
	c.StreamCreateRowScanner(qw422016, r, camelName)
//line database_tpl.qtpl:245
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:245
}

//line database_tpl.qtpl:245
func (c *Creator) CreateRowScanner(r *psql.Routine, camelName string) string {
//line database_tpl.qtpl:245
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:245
	c.WriteCreateRowScanner(qb422016, r, camelName)
//line database_tpl.qtpl:245
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:245
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:245
	return qs422016
//line database_tpl.qtpl:245
}

//line database_tpl.qtpl:247
func (c *Creator) streamparamsTitle(qw422016 *qt422016.Writer, r *psql.Routine) {
//line database_tpl.qtpl:248
	for _, param := range r.Params() {
//line database_tpl.qtpl:250
		s := strcase.ToLowerCamel(param.Name())
		typeCol, _ := c.chkTypes(param, s)

//line database_tpl.qtpl:252
		qw422016.N().S(`	`)
//line database_tpl.qtpl:253
		qw422016.E().S(s)
//line database_tpl.qtpl:253
		qw422016.N().S(` `)
//line database_tpl.qtpl:253
		qw422016.E().S(typeCol)
//line database_tpl.qtpl:253
		qw422016.N().S(`,
`)
//line database_tpl.qtpl:254
	}
//line database_tpl.qtpl:255
}

//line database_tpl.qtpl:255
func (c *Creator) writeparamsTitle(qq422016 qtio422016.Writer, r *psql.Routine) {
//line database_tpl.qtpl:255
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:255
	c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:255
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:255
}

//line database_tpl.qtpl:255
func (c *Creator) paramsTitle(r *psql.Routine) string {
//line database_tpl.qtpl:255
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:255
	c.writeparamsTitle(qb422016, r)
//line database_tpl.qtpl:255
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:255
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:255
	return qs422016
//line database_tpl.qtpl:255
}

//line database_tpl.qtpl:256
func (c *Creator) streamparamsArgs(qw422016 *qt422016.Writer, r *psql.Routine) {
//line database_tpl.qtpl:257
	for _, param := range r.Params() {
//line database_tpl.qtpl:257
		qw422016.N().S(`	`)
//line database_tpl.qtpl:258
		qw422016.E().S(strcase.ToLowerCamel(param.Name()))
//line database_tpl.qtpl:258
		qw422016.N().S(`,
`)
//line database_tpl.qtpl:259
	}
//line database_tpl.qtpl:260
}

//line database_tpl.qtpl:260
func (c *Creator) writeparamsArgs(qq422016 qtio422016.Writer, r *psql.Routine) {
//line database_tpl.qtpl:260
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:260
	c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:260
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:260
}

//line database_tpl.qtpl:260
func (c *Creator) paramsArgs(r *psql.Routine) string {
//line database_tpl.qtpl:260
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:260
	c.writeparamsArgs(qb422016, r)
//line database_tpl.qtpl:260
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:260
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:260
	return qs422016
//line database_tpl.qtpl:260
}

//line database_tpl.qtpl:262
func (c *Creator) StreamCreateTableConstructor(qw422016 *qt422016.Writer, cName, name string) {
//line database_tpl.qtpl:262
	qw422016.N().S(`// New`)
//line database_tpl.qtpl:263
	qw422016.E().S(cName)
//line database_tpl.qtpl:263
	qw422016.N().S(` create new instance of table `)
//line database_tpl.qtpl:263
	qw422016.E().S(cName)
//line database_tpl.qtpl:263
	qw422016.N().S(`
func (d *Database) New`)
//line database_tpl.qtpl:264
	qw422016.E().S(cName)
//line database_tpl.qtpl:264
	qw422016.N().S(`(ctx context.Context) (*`)
//line database_tpl.qtpl:264
	qw422016.E().S(cName)
//line database_tpl.qtpl:264
	qw422016.N().S(`, error) {
	const name = "`)
//line database_tpl.qtpl:265
	qw422016.E().S(name)
//line database_tpl.qtpl:265
	qw422016.N().S(`"
	table, ok := d.Tables[name]
    if !ok {
		var err error
		table, err = New`)
//line database_tpl.qtpl:269
	qw422016.E().S(cName)
//line database_tpl.qtpl:269
	qw422016.N().S(`FromConn(ctx, d.PsqlConn())
		if err != nil {
			return nil, err
		}
		d.Tables[name] = table
    }

    return &`)
//line database_tpl.qtpl:276
	qw422016.E().S(cName)
//line database_tpl.qtpl:276
	qw422016.N().S(`{
		Table: table.(*psql.Table),
    }, nil
}
`)
//line database_tpl.qtpl:280
}

//line database_tpl.qtpl:280
func (c *Creator) WriteCreateTableConstructor(qq422016 qtio422016.Writer, cName, name string) {
//line database_tpl.qtpl:280
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:280
	c.StreamCreateTableConstructor(qw422016, cName, name)
//line database_tpl.qtpl:280
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:280
}

//line database_tpl.qtpl:280
func (c *Creator) CreateTableConstructor(cName, name string) string {
//line database_tpl.qtpl:280
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:280
	c.WriteCreateTableConstructor(qb422016, cName, name)
//line database_tpl.qtpl:280
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:280
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:280
	return qs422016
//line database_tpl.qtpl:280
}
