// Code generated by qtc from "database_tpl.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line database_tpl.qtpl:1
package _go

//line database_tpl.qtpl:2
import (
	"fmt"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/ruslanBik4/dbEngine/dbEngine"
	"github.com/ruslanBik4/dbEngine/dbEngine/psql"
)

//line database_tpl.qtpl:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line database_tpl.qtpl:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line database_tpl.qtpl:12
func (c *Creator) StreamCreateDatabase(qw422016 *qt422016.Writer, listRoutines []string) {
//line database_tpl.qtpl:12
	qw422016.N().S(`
// Code generated by dbEngine-gen-go. DO NOT EDIT!
// Copyright https://github.com/ruslanBik4

/*
DB implements interface for table, view and routines of Database
versions:
 	dbEngine v1.1.6
source: %s %s
*/
package db

import (
	"bytes"
	"fmt"
	"errors"
	"time"
	"strings"
`)
//line database_tpl.qtpl:30
	for _, lib := range c.packages {
//line database_tpl.qtpl:30
		qw422016.N().S(`"`)
//line database_tpl.qtpl:30
		qw422016.E().S(lib)
//line database_tpl.qtpl:30
		qw422016.N().S(`"
`)
//line database_tpl.qtpl:31
	}
//line database_tpl.qtpl:31
	qw422016.N().S(`
	"github.com/jackc/pgx/v4"
	"github.com/jackc/pgconn"
	"github.com/jackc/pgtype"

	"github.com/ruslanBik4/logs"
	"github.com/ruslanBik4/dbEngine/dbEngine"
    "github.com/ruslanBik4/dbEngine/dbEngine/psql"

	"golang.org/x/net/context"
)
type scanError interface{
	ScanValue(d any)
	Err() error
}

`)
//line database_tpl.qtpl:48
	for name, typ := range c.db.Types {
//line database_tpl.qtpl:48
		c.StreamCreateTypeInterface(qw422016, typ, strcase.ToCamel(name), name, c.Types[name])
//line database_tpl.qtpl:48
	}
//line database_tpl.qtpl:48
	qw422016.N().S(`
type CitextArray struct {
	pgtype.TextArray
}

func (dst CitextArray) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBufferString("[")
	for i, text := range dst.Elements {
		if i > 0 {
			buf.WriteString(",")
		}

		buf.WriteString(text.String)
	}

	buf.WriteString("]")

	return buf.Bytes(), nil
}

var customTypes = map[string]*pgtype.DataType{
	"citext": &pgtype.DataType{
		Value: &pgtype.Text{},
		Name:  "citext",
	},
	"_citext": &pgtype.DataType{
		Value: &pgtype.TextArray{}, // (*pgtype.ArrayType)(nil),
		Name:  "[]string",
	},
}
var initCustomTypes bool

const sqlGetTypes = "SELECT typname, oid FROM pg_type WHERE typname::text=ANY($1)"

func getOidCustomTypes(ctx context.Context, conn *pgx.Conn) error {
	params := make([]string, 0, len(customTypes))
	for name := range customTypes {
		params = append(params, name)
	}

	rows, err := conn.Query(ctx, sqlGetTypes, params)
	if err != nil {
		return err
	}

	for rows.Next() {
		var name string
		var oid uint32
		err = rows.Scan(&name, &oid)
		if err != nil {
			return err
		}
		if c, ok := customTypes[name]; ok && c.Value == (*pgtype.ArrayType)(nil) {
			c.Value = pgtype.NewArrayType(name, oid, func() pgtype.ValueTranscoder {
				return &pgtype.Text{}
			}).NewTypeValue()
			c.OID = oid
			logs.DebugLog(c)
		} else if ok {
			customTypes[name].OID = oid
		}
	}

	if rows.Err() != nil {
		logs.ErrorLog(rows.Err(), " cannot get oid for customTypes")
	}

	return err
}

// afterConnect create need types & register on conn
func afterConnect(ctx context.Context, conn *pgx.Conn) error {
	// Override registered handler for point
	if !initCustomTypes {
		err := getOidCustomTypes(ctx, conn)
		if err != nil {
			return err
		}

		initCustomTypes = true
	}

	mess := "DB registered type (name, oid): "
	for name, val := range customTypes {
		conn.ConnInfo().RegisterDataType(*val)
		mess += fmt.Sprintf("(%s,%v, %T) ", name, val.OID, val.Value)
	}

	logs.StatusLog(conn.PgConn().Conn().LocalAddr().String(), mess)

	return nil
}

// Database is root interface for operation for %s.%s
type Database struct {
	*dbEngine.DB
	CreateAt time.Time
}
// NewDatabase create new Database with minimal necessary handlers
func NewDatabase(ctx context.Context, noticeHandler pgconn.NoticeHandler, channelHandler pgconn.NotificationHandler, channels ...string) (*Database, error) {
	if noticeHandler == nil {
		noticeHandler = printNotice
	}
	conn := psql.NewConnWithOptions(
		psql.AfterConnect(afterConnect),
		psql.NoticeHandler(noticeHandler),
		psql.ChannelHandler(channelHandler),
		psql.Channels(channels...),
	)

	DB, err := dbEngine.NewDB(ctx, conn)
	if err != nil {
		logs.ErrorLog(err, "new DB")
		return nil, err
	}

	return &Database{DB, time.Now()}, nil
}
// PsqlConn return connection as *psql.Conn
// need for some low-level operation,
// invoke Conn.Select...(custom sql),
//        New{table_name}FromConn, etc.
func (d *Database) PsqlConn() *psql.Conn {
	return (d.Conn).(*psql.Conn)
}
`)
//line database_tpl.qtpl:174
	for name := range c.db.Tables {
//line database_tpl.qtpl:174
		c.StreamCreateTableConstructor(qw422016, strcase.ToCamel(name), name)
//line database_tpl.qtpl:174
	}
//line database_tpl.qtpl:175
	for _, name := range listRoutines {
//line database_tpl.qtpl:175
		c.StreamCreateRoutinesInvoker(qw422016, c.db.Routines[name].(*psql.Routine), name)
//line database_tpl.qtpl:175
	}
//line database_tpl.qtpl:175
	qw422016.N().S(`// printNotice logging some psql messages (invoked command 'RAISE ...')
func printNotice(c *pgconn.PgConn, n *pgconn.Notice) {

	switch {
    case n.Code == "42P07" || strings.Contains(n.Message, "skipping") :
		logs.DebugLog("skip operation: %s", n.Message)

	case n.Severity == "INFO" :
		logs.StatusLog(n.Message)

	case n.Code > "00000" :
		err := (*pgconn.PgError)(n)
		logs.CustomLog(logs.CRITICAL, "DB_EXEC",  err.File, int(err.Line),
			fmt.Sprintf("%v, hint: %s, where: %s, %s %s", err, n.Hint, n.Where,  err.SQLState(), err.Routine), logs.FgErr)

	case strings.HasPrefix(n.Message, "[[ERROR]]") :
		logs.ErrorLog(errors.New(strings.TrimPrefix(n.Message, "[[ERROR]]") + n.Severity))

	default: // DEBUG
		logs.DebugLog("%+v %s (PID:%d)", n.Severity, n.Message, c.PID())
	}
}
`)
//line database_tpl.qtpl:198
}

//line database_tpl.qtpl:198
func (c *Creator) WriteCreateDatabase(qq422016 qtio422016.Writer, listRoutines []string) {
//line database_tpl.qtpl:198
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:198
	c.StreamCreateDatabase(qw422016, listRoutines)
//line database_tpl.qtpl:198
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:198
}

//line database_tpl.qtpl:198
func (c *Creator) CreateDatabase(listRoutines []string) string {
//line database_tpl.qtpl:198
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:198
	c.WriteCreateDatabase(qb422016, listRoutines)
//line database_tpl.qtpl:198
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:198
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:198
	return qs422016
//line database_tpl.qtpl:198
}

//line database_tpl.qtpl:200
func (c *Creator) StreamCreateTypeInterface(qw422016 *qt422016.Writer, t dbEngine.Types, typeName, name, typeCol string) {
//line database_tpl.qtpl:201
	if len(t.Enumerates) > 0 {
//line database_tpl.qtpl:202
	} else {
//line database_tpl.qtpl:202
		qw422016.N().S(`// `)
//line database_tpl.qtpl:203
		qw422016.E().S(typeName)
//line database_tpl.qtpl:203
		qw422016.N().S(` create new instance of type `)
//line database_tpl.qtpl:203
		qw422016.E().S(name)
//line database_tpl.qtpl:203
		qw422016.N().S(`
type `)
//line database_tpl.qtpl:204
		qw422016.E().S(typeName)
//line database_tpl.qtpl:204
		qw422016.N().S(` struct {
`)
//line database_tpl.qtpl:205
		for _, attr := range t.Attr {
//line database_tpl.qtpl:205
			qw422016.N().S(`	`)
//line database_tpl.qtpl:206
			qw422016.N().S(fmt.Sprintf("%-21s\t%-13s\t", strcase.ToCamel(attr.Name), attr.Type))
//line database_tpl.qtpl:206
			qw422016.N().S(` `)
//line database_tpl.qtpl:206
			qw422016.N().S("`")
//line database_tpl.qtpl:206
			qw422016.N().S(`json:"`)
//line database_tpl.qtpl:206
			qw422016.E().S(attr.Name)
//line database_tpl.qtpl:206
			qw422016.N().S(`"`)
//line database_tpl.qtpl:206
			qw422016.N().S("`")
//line database_tpl.qtpl:206
			qw422016.N().S(`
`)
//line database_tpl.qtpl:207
		}
//line database_tpl.qtpl:208
		if t.Type == 'r' {
//line database_tpl.qtpl:208
			qw422016.N().S(`	LowerType pgtype.BoundType
	UpperType pgtype.BoundType
`)
//line database_tpl.qtpl:211
		}
//line database_tpl.qtpl:211
		qw422016.N().S(`}
// DecodeText implement pgtype.TextDecoder interface
func (dst *`)
//line database_tpl.qtpl:214
		qw422016.E().S(typeName)
//line database_tpl.qtpl:214
		qw422016.N().S(`) DecodeText(ci *pgtype.ConnInfo, src []byte) error {
	if len(src) == 0 {
		*dst = `)
//line database_tpl.qtpl:216
		qw422016.E().S(typeName)
//line database_tpl.qtpl:216
		qw422016.N().S(`{}
		return nil
	}
`)
//line database_tpl.qtpl:219
		if t.Type == 'r' {
//line database_tpl.qtpl:219
			qw422016.N().S(`	utr, err := pgtype.ParseUntypedTextRange(gotools.BytesToString(src))
	if err != nil {
		return err
	}
`)
//line database_tpl.qtpl:224
		} else {
//line database_tpl.qtpl:224
			qw422016.N().S(`	c := pgtype.NewCompositeTextScanner(ci, src)
`)
//line database_tpl.qtpl:226
		}
//line database_tpl.qtpl:226
		qw422016.N().S(`    *dst = `)
//line database_tpl.qtpl:227
		qw422016.E().S(typeName)
//line database_tpl.qtpl:227
		qw422016.N().S(`{}
	var scanErrors error

`)
//line database_tpl.qtpl:230
		if t.Type == 'r' {
//line database_tpl.qtpl:230
			qw422016.N().S(`    	dst.LowerType = utr.LowerType
    	dst.UpperType = utr.UpperType

    	if dst.LowerType == pgtype.Empty {
    		return nil
    	}

    	var scanErrors error
    	if dst.LowerType == pgtype.Inclusive || dst.LowerType == pgtype.Exclusive {
    		if err := dst.Lower.DecodeText(ci, gotools.StringToBytes(utr.Lower)); err != nil {
    			scanErrors = errors.Join(scanErrors, err)
    		}
    	}

    	if dst.UpperType == pgtype.Inclusive || dst.UpperType == pgtype.Exclusive {
    		if err := dst.Upper.DecodeText(ci, gotools.StringToBytes(utr.Upper)); err != nil {
    			scanErrors = errors.Join(scanErrors, err)
    		}
    	}
`)
//line database_tpl.qtpl:250
		} else {
//line database_tpl.qtpl:250
			qw422016.N().S(`
`)
//line database_tpl.qtpl:252
			for _, attr := range t.Attr {
//line database_tpl.qtpl:252
				qw422016.N().S(`	`)
//line database_tpl.qtpl:253
				if strings.HasPrefix(attr.Name, "pgtype.") || strings.HasPrefix(attr.Name, "psql.") {
//line database_tpl.qtpl:253
					qw422016.N().S(`c.ScanDecoder
`)
//line database_tpl.qtpl:254
				} else {
//line database_tpl.qtpl:254
					qw422016.N().S(`c.ScanValue`)
//line database_tpl.qtpl:254
				}
//line database_tpl.qtpl:254
				qw422016.N().S(`	(&dst.`)
//line database_tpl.qtpl:255
				qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:255
				qw422016.N().S(`)
	if err := c.Err(); err != nil {
		logs.ErrorLog(err, "`)
//line database_tpl.qtpl:257
				qw422016.E().S(typeName)
//line database_tpl.qtpl:257
				qw422016.N().S(`.`)
//line database_tpl.qtpl:257
				qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:257
				qw422016.N().S(`")
		scanErrors = errors.Join(scanErrors, err)
	}
`)
//line database_tpl.qtpl:260
			}
//line database_tpl.qtpl:261
		}
//line database_tpl.qtpl:261
		qw422016.N().S(`
	return scanError
}
// DecodeBinary implement pgtype.BinaryDecoder interface
func (dst *`)
//line database_tpl.qtpl:266
		qw422016.E().S(typeName)
//line database_tpl.qtpl:266
		qw422016.N().S(`) DecodeBinary(ci *pgtype.ConnInfo, src []byte) error {
	if len(src) == 0 {
		*dst = `)
//line database_tpl.qtpl:268
		qw422016.E().S(typeName)
//line database_tpl.qtpl:268
		qw422016.N().S(`{}
		return nil
	}

`)
//line database_tpl.qtpl:272
		if t.Type == 'r' {
//line database_tpl.qtpl:272
			qw422016.N().S(`	utr, err := pgtype.ParseUntypedBinaryRange(src)
	if err != nil {
		return err
	}
`)
//line database_tpl.qtpl:277
		} else {
//line database_tpl.qtpl:277
			qw422016.N().S(`	c := pgtype.NewCompositeBinaryScanner(ci, src)
	countFields := c.FieldCount()
`)
//line database_tpl.qtpl:280
		}
//line database_tpl.qtpl:280
		qw422016.N().S(`    *dst = `)
//line database_tpl.qtpl:281
		qw422016.E().S(typeName)
//line database_tpl.qtpl:281
		qw422016.N().S(`{}
	var scanErrors error

`)
//line database_tpl.qtpl:284
		if t.Type == 'r' {
//line database_tpl.qtpl:284
			qw422016.N().S(`    	dst.LowerType = utr.LowerType
    	dst.UpperType = utr.UpperType

    	if dst.LowerType == pgtype.Empty {
    		return nil
    	}

    	if dst.LowerType == pgtype.Inclusive || dst.LowerType == pgtype.Exclusive {
    		if err := dst.Lower.DecodeBinary(ci, utr.Lower); err != nil {
    			scanErrors = errors.Join(scanErrors, err)
    		}
    	}

    	if dst.UpperType == pgtype.Inclusive || dst.UpperType == pgtype.Exclusive {
    		if err := dst.Upper.DecodeBinary(ci, utr.Upper); err != nil {
    			scanErrors = errors.Join(scanErrors, err)
    		}
    	}
`)
//line database_tpl.qtpl:303
		} else {
//line database_tpl.qtpl:304
			for i, attr := range t.Attr {
//line database_tpl.qtpl:304
				qw422016.N().S(`	//	    rich end of elements
	if  countFields < `)
//line database_tpl.qtpl:306
				qw422016.N().D(i + 1)
//line database_tpl.qtpl:306
				qw422016.N().S(` || !c.Next(){
		return nil
	}
	if err := `)
//line database_tpl.qtpl:309
				if strings.HasPrefix(attr.Name, "pgtype.") || strings.HasPrefix(attr.Name, "psql.") {
//line database_tpl.qtpl:309
					qw422016.N().S(`&dst.`)
//line database_tpl.qtpl:309
					qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:309
					qw422016.N().S(`.DecodeBinary(ci, c.Bytes())
`)
//line database_tpl.qtpl:310
				} else {
//line database_tpl.qtpl:310
					qw422016.N().S(`ci.Scan(c.OID(), pgtype.BinaryFormatCode, c.Bytes(), &dst.`)
//line database_tpl.qtpl:310
					qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:310
					qw422016.N().S(`)`)
//line database_tpl.qtpl:310
				}
//line database_tpl.qtpl:310
				qw422016.N().S(`; err != nil {
		logs.ErrorLog(err, "`)
//line database_tpl.qtpl:311
				qw422016.E().S(typeName)
//line database_tpl.qtpl:311
				qw422016.N().S(`.`)
//line database_tpl.qtpl:311
				qw422016.E().S(strcase.ToCamel(attr.Name))
//line database_tpl.qtpl:311
				qw422016.N().S(`")
		scanErrors = errors.Join(scanErrors, err)
	}
`)
//line database_tpl.qtpl:314
			}
//line database_tpl.qtpl:315
		}
//line database_tpl.qtpl:315
		qw422016.N().S(`
	return scanErrors
}
// Scan implement sql.Scanner interface
func (dst *`)
//line database_tpl.qtpl:320
		qw422016.E().S(typeName)
//line database_tpl.qtpl:320
		qw422016.N().S(`) Scan(src any) error {
	switch src := src.(type) {
	case nil:
		*dst = `)
//line database_tpl.qtpl:323
		qw422016.E().S(typeName)
//line database_tpl.qtpl:323
		qw422016.N().S(`{}
	case string:
		return dst.DecodeText(nil, gotools.StringToBytes(src))
	case []byte:
		return dst.DecodeText(nil, src)
	default:
		return fmt.Errorf("cannot scan %T", src)
	}
}
`)
//line database_tpl.qtpl:332
	}
//line database_tpl.qtpl:333
}

//line database_tpl.qtpl:333
func (c *Creator) WriteCreateTypeInterface(qq422016 qtio422016.Writer, t dbEngine.Types, typeName, name, typeCol string) {
//line database_tpl.qtpl:333
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:333
	c.StreamCreateTypeInterface(qw422016, t, typeName, name, typeCol)
//line database_tpl.qtpl:333
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:333
}

//line database_tpl.qtpl:333
func (c *Creator) CreateTypeInterface(t dbEngine.Types, typeName, name, typeCol string) string {
//line database_tpl.qtpl:333
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:333
	c.WriteCreateTypeInterface(qb422016, t, typeName, name, typeCol)
//line database_tpl.qtpl:333
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:333
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:333
	return qs422016
//line database_tpl.qtpl:333
}

// end CreateTypeInterface
//

//line database_tpl.qtpl:336
func (c *Creator) StreamCreateRoutinesInvoker(qw422016 *qt422016.Writer, r *psql.Routine, name string) {
//line database_tpl.qtpl:338
	camelName := strcase.ToCamel(name)
	args := make([]any, len(r.Params()))
	sql, _, _ := r.BuildSql(dbEngine.ArgsForSelect(args...))
	typeReturn := ""

//line database_tpl.qtpl:343
	if r.Type == psql.ROUTINE_TYPE_PROC {
//line database_tpl.qtpl:343
		qw422016.N().S(`// `)
//line database_tpl.qtpl:344
		qw422016.E().S(camelName)
//line database_tpl.qtpl:344
		qw422016.N().S(` call procedure '`)
//line database_tpl.qtpl:344
		qw422016.E().S(name)
//line database_tpl.qtpl:344
		qw422016.N().S(`'
// DB comment: '`)
//line database_tpl.qtpl:345
		qw422016.E().S(r.Comment)
//line database_tpl.qtpl:345
		qw422016.N().S(`'
func (d *Database) `)
//line database_tpl.qtpl:346
		qw422016.E().S(camelName)
//line database_tpl.qtpl:346
		qw422016.N().S(`(ctx context.Context,
				`)
//line database_tpl.qtpl:347
		c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:347
		qw422016.N().S(`
) error {
	return d.Conn.ExecDDL(ctx,
				`)
//line database_tpl.qtpl:347
		qw422016.N().S("`")
//line database_tpl.qtpl:350
		qw422016.E().S(sql)
//line database_tpl.qtpl:350
		qw422016.N().S(``)
//line database_tpl.qtpl:350
		qw422016.N().S("`")
//line database_tpl.qtpl:350
		qw422016.N().S(`,
				`)
//line database_tpl.qtpl:351
		c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:351
		qw422016.N().S(`
			)
}
`)
//line database_tpl.qtpl:354
	} else {
//line database_tpl.qtpl:355
		switch len(r.Columns()) {
//line database_tpl.qtpl:356
		case 0:
//line database_tpl.qtpl:357
			typeReturn = c.udtToReturnType(r.UdtName)

//line database_tpl.qtpl:358
		case 1:
//line database_tpl.qtpl:360
			param := r.Columns()[0]
			typeReturn, _ = c.chkTypes(param, strcase.ToCamel(param.Name()))

//line database_tpl.qtpl:363
		default:
//line database_tpl.qtpl:364
			typeReturn = fmt.Sprintf("*%sRowScanner", camelName)

//line database_tpl.qtpl:365
			c.StreamCreateRowScanner(qw422016, r, camelName)
//line database_tpl.qtpl:365
			qw422016.N().S(`
`)
//line database_tpl.qtpl:366
		}
//line database_tpl.qtpl:366
		qw422016.N().S(`// `)
//line database_tpl.qtpl:367
		qw422016.E().S(camelName)
//line database_tpl.qtpl:367
		qw422016.N().S(` run query with select DB function '`)
//line database_tpl.qtpl:367
		qw422016.E().S(name)
//line database_tpl.qtpl:367
		qw422016.N().S(`: `)
//line database_tpl.qtpl:367
		qw422016.E().S(r.UdtName)
//line database_tpl.qtpl:367
		qw422016.N().S(`'
// DB comment: '`)
//line database_tpl.qtpl:368
		qw422016.E().S(r.Comment)
//line database_tpl.qtpl:368
		qw422016.N().S(`'
// ATTENTION! It returns only 1 row `)
//line database_tpl.qtpl:369
		qw422016.E().S(typeReturn)
//line database_tpl.qtpl:369
		qw422016.N().S(`
func (d *Database) `)
//line database_tpl.qtpl:370
		qw422016.E().S(camelName)
//line database_tpl.qtpl:370
		qw422016.N().S(`(
	ctx context.Context,
`)
//line database_tpl.qtpl:372
		c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:372
		qw422016.N().S(`) (res `)
//line database_tpl.qtpl:372
		qw422016.E().S(typeReturn)
//line database_tpl.qtpl:372
		qw422016.N().S(`, err error) {
	err = d.Conn.SelectOneAndScan(ctx,
		&res,
		`)
//line database_tpl.qtpl:372
		qw422016.N().S("`")
//line database_tpl.qtpl:375
		qw422016.E().S(sql)
//line database_tpl.qtpl:375
		qw422016.N().S(`
		FETCH FIRST 1 ROW ONLY`)
//line database_tpl.qtpl:375
		qw422016.N().S("`")
//line database_tpl.qtpl:375
		qw422016.N().S(`,
		`)
//line database_tpl.qtpl:377
		c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:377
		qw422016.N().S(`      )

	return
}
`)
//line database_tpl.qtpl:381
		if r.ReturnType() == "record" {
//line database_tpl.qtpl:382
			typeReturn = fmt.Sprintf("%sRowScanner", camelName)

//line database_tpl.qtpl:382
			qw422016.N().S(`// `)
//line database_tpl.qtpl:383
			qw422016.E().S(camelName)
//line database_tpl.qtpl:383
			qw422016.N().S(`Each run query with select DB function '`)
//line database_tpl.qtpl:383
			qw422016.E().S(name)
//line database_tpl.qtpl:383
			qw422016.N().S(`'
// DB comment: '`)
//line database_tpl.qtpl:384
			qw422016.E().S(r.Comment)
//line database_tpl.qtpl:384
			qw422016.N().S(`'
// each will get every row from &`)
//line database_tpl.qtpl:385
			qw422016.E().S(camelName)
//line database_tpl.qtpl:385
			qw422016.N().S(`sRowScanner
func (d *Database) `)
//line database_tpl.qtpl:386
			qw422016.E().S(camelName)
//line database_tpl.qtpl:386
			qw422016.N().S(`Each(
	ctx context.Context,
	each func(record *`)
//line database_tpl.qtpl:388
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:388
			qw422016.N().S(`) error,
`)
//line database_tpl.qtpl:389
			c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:389
			qw422016.N().S(`) error {
	res := &`)
//line database_tpl.qtpl:390
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:390
			qw422016.N().S(`{}
	err := d.Conn.SelectAndScanEach(ctx,
		func () error {
			defer func () {
			//	create new record
				*res = `)
//line database_tpl.qtpl:395
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:395
			qw422016.N().S(`{}
			}()

			if each != nil {
				return each(res)
			}
			return nil
		},
		res,
		`)
//line database_tpl.qtpl:395
			qw422016.N().S("`")
//line database_tpl.qtpl:404
			qw422016.E().S(sql)
//line database_tpl.qtpl:404
			qw422016.N().S(``)
//line database_tpl.qtpl:404
			qw422016.N().S("`")
//line database_tpl.qtpl:404
			qw422016.N().S(`,
`)
//line database_tpl.qtpl:405
			c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:405
			qw422016.N().S(`      )

	return err
}
// `)
//line database_tpl.qtpl:409
			qw422016.E().S(camelName)
//line database_tpl.qtpl:409
			qw422016.N().S(`All run query with select DB function '`)
//line database_tpl.qtpl:409
			qw422016.E().S(name)
//line database_tpl.qtpl:409
			qw422016.N().S(`'
// DB comment: '`)
//line database_tpl.qtpl:410
			qw422016.E().S(r.Comment)
//line database_tpl.qtpl:410
			qw422016.N().S(`'
// each will get every row from &`)
//line database_tpl.qtpl:411
			qw422016.E().S(camelName)
//line database_tpl.qtpl:411
			qw422016.N().S(`sRowScanner
func (d *Database) `)
//line database_tpl.qtpl:412
			qw422016.E().S(camelName)
//line database_tpl.qtpl:412
			qw422016.N().S(`All(
	ctx context.Context,
`)
//line database_tpl.qtpl:414
			c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:414
			qw422016.N().S(`) (res []`)
//line database_tpl.qtpl:414
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:414
			qw422016.N().S(`, err error) {
	buf := `)
//line database_tpl.qtpl:415
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:415
			qw422016.N().S(`{}
	err = d.Conn.SelectAndScanEach(ctx,
		func () error {
			res = append(res, buf)
			//	create new record
			buf = `)
//line database_tpl.qtpl:420
			qw422016.E().S(typeReturn)
//line database_tpl.qtpl:420
			qw422016.N().S(`{}

			return nil
		},
		&buf,
		`)
//line database_tpl.qtpl:420
			qw422016.N().S("`")
//line database_tpl.qtpl:425
			qw422016.E().S(sql)
//line database_tpl.qtpl:425
			qw422016.N().S(``)
//line database_tpl.qtpl:425
			qw422016.N().S("`")
//line database_tpl.qtpl:425
			qw422016.N().S(`,
`)
//line database_tpl.qtpl:426
			c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:426
			qw422016.N().S(`      )

	return
}
`)
//line database_tpl.qtpl:430
		}
//line database_tpl.qtpl:430
		qw422016.N().S(`

`)
//line database_tpl.qtpl:432
	}
//line database_tpl.qtpl:432
	qw422016.N().S(`
`)
//line database_tpl.qtpl:433
}

//line database_tpl.qtpl:433
func (c *Creator) WriteCreateRoutinesInvoker(qq422016 qtio422016.Writer, r *psql.Routine, name string) {
//line database_tpl.qtpl:433
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:433
	c.StreamCreateRoutinesInvoker(qw422016, r, name)
//line database_tpl.qtpl:433
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:433
}

//line database_tpl.qtpl:433
func (c *Creator) CreateRoutinesInvoker(r *psql.Routine, name string) string {
//line database_tpl.qtpl:433
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:433
	c.WriteCreateRoutinesInvoker(qb422016, r, name)
//line database_tpl.qtpl:433
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:433
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:433
	return qs422016
//line database_tpl.qtpl:433
}

//line database_tpl.qtpl:435
func (c *Creator) StreamCreateRowScanner(qw422016 *qt422016.Writer, r *psql.Routine, camelName string) {
//line database_tpl.qtpl:435
	qw422016.N().S(`// `)
//line database_tpl.qtpl:436
	qw422016.E().S(camelName)
//line database_tpl.qtpl:436
	qw422016.N().S(`RowScanner run query with select
type `)
//line database_tpl.qtpl:437
	qw422016.E().S(camelName)
//line database_tpl.qtpl:437
	qw422016.N().S(`RowScanner struct {
`)
//line database_tpl.qtpl:438
	for _, param := range r.Columns() {
//line database_tpl.qtpl:440
		s := strcase.ToCamel(param.Name())
		typeCol, _ := c.chkTypes(param, s)

//line database_tpl.qtpl:442
		qw422016.N().S(`	`)
//line database_tpl.qtpl:443
		qw422016.E().S(s)
//line database_tpl.qtpl:443
		qw422016.E().S("\t\t")
//line database_tpl.qtpl:443
		qw422016.E().S(typeCol)
//line database_tpl.qtpl:443
		qw422016.E().S("\t\t")
//line database_tpl.qtpl:443
		qw422016.N().S(``)
//line database_tpl.qtpl:443
		qw422016.N().S("`")
//line database_tpl.qtpl:443
		qw422016.N().S(`json:"`)
//line database_tpl.qtpl:443
		qw422016.E().S(param.Name())
//line database_tpl.qtpl:443
		qw422016.N().S(`"`)
//line database_tpl.qtpl:443
		qw422016.N().S("`")
//line database_tpl.qtpl:443
		qw422016.N().S(`
`)
//line database_tpl.qtpl:444
	}
//line database_tpl.qtpl:444
	qw422016.N().S(`}
// GetFields implement dbEngine.RowScanner interface
func (r *`)
//line database_tpl.qtpl:447
	qw422016.E().S(camelName)
//line database_tpl.qtpl:447
	qw422016.N().S(`RowScanner) GetFields(columns []dbEngine.Column) []any {
	v := make([]any, len(columns))
	for i, col := range columns {
		switch col.Name() {
`)
//line database_tpl.qtpl:451
	for _, param := range r.Columns() {
//line database_tpl.qtpl:451
		qw422016.N().S(`		case "`)
//line database_tpl.qtpl:452
		qw422016.E().S(param.Name())
//line database_tpl.qtpl:452
		qw422016.N().S(`":
			v[i] =  &r.`)
//line database_tpl.qtpl:453
		qw422016.N().S(strcase.ToCamel(param.Name()))
//line database_tpl.qtpl:453
		qw422016.N().S(`
`)
//line database_tpl.qtpl:454
	}
//line database_tpl.qtpl:454
	qw422016.N().S(`		}
	}

	return v
}
`)
//line database_tpl.qtpl:460
}

//line database_tpl.qtpl:460
func (c *Creator) WriteCreateRowScanner(qq422016 qtio422016.Writer, r *psql.Routine, camelName string) {
//line database_tpl.qtpl:460
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:460
	c.StreamCreateRowScanner(qw422016, r, camelName)
//line database_tpl.qtpl:460
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:460
}

//line database_tpl.qtpl:460
func (c *Creator) CreateRowScanner(r *psql.Routine, camelName string) string {
//line database_tpl.qtpl:460
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:460
	c.WriteCreateRowScanner(qb422016, r, camelName)
//line database_tpl.qtpl:460
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:460
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:460
	return qs422016
//line database_tpl.qtpl:460
}

//line database_tpl.qtpl:462
func (c *Creator) streamparamsTitle(qw422016 *qt422016.Writer, r *psql.Routine) {
//line database_tpl.qtpl:463
	for _, param := range r.Params() {
//line database_tpl.qtpl:465
		s := strcase.ToLowerCamel(param.Name())
		typeCol, _ := c.chkTypes(param, s)

//line database_tpl.qtpl:467
		qw422016.N().S(`	`)
//line database_tpl.qtpl:468
		qw422016.E().S(s)
//line database_tpl.qtpl:468
		qw422016.E().S("\t\t")
//line database_tpl.qtpl:468
		qw422016.E().S(typeCol)
//line database_tpl.qtpl:468
		qw422016.N().S(`,
`)
//line database_tpl.qtpl:469
	}
//line database_tpl.qtpl:470
}

//line database_tpl.qtpl:470
func (c *Creator) writeparamsTitle(qq422016 qtio422016.Writer, r *psql.Routine) {
//line database_tpl.qtpl:470
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:470
	c.streamparamsTitle(qw422016, r)
//line database_tpl.qtpl:470
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:470
}

//line database_tpl.qtpl:470
func (c *Creator) paramsTitle(r *psql.Routine) string {
//line database_tpl.qtpl:470
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:470
	c.writeparamsTitle(qb422016, r)
//line database_tpl.qtpl:470
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:470
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:470
	return qs422016
//line database_tpl.qtpl:470
}

//line database_tpl.qtpl:471
func (c *Creator) streamparamsArgs(qw422016 *qt422016.Writer, r *psql.Routine) {
//line database_tpl.qtpl:472
	for _, param := range r.Params() {
//line database_tpl.qtpl:472
		qw422016.N().S(`		`)
//line database_tpl.qtpl:473
		qw422016.E().S(strcase.ToLowerCamel(param.Name()))
//line database_tpl.qtpl:473
		qw422016.N().S(`,
`)
//line database_tpl.qtpl:474
	}
//line database_tpl.qtpl:475
}

//line database_tpl.qtpl:475
func (c *Creator) writeparamsArgs(qq422016 qtio422016.Writer, r *psql.Routine) {
//line database_tpl.qtpl:475
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:475
	c.streamparamsArgs(qw422016, r)
//line database_tpl.qtpl:475
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:475
}

//line database_tpl.qtpl:475
func (c *Creator) paramsArgs(r *psql.Routine) string {
//line database_tpl.qtpl:475
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:475
	c.writeparamsArgs(qb422016, r)
//line database_tpl.qtpl:475
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:475
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:475
	return qs422016
//line database_tpl.qtpl:475
}

//line database_tpl.qtpl:477
func (c *Creator) StreamCreateTableConstructor(qw422016 *qt422016.Writer, cName, name string) {
//line database_tpl.qtpl:477
	qw422016.N().S(`// New`)
//line database_tpl.qtpl:478
	qw422016.E().S(cName)
//line database_tpl.qtpl:478
	qw422016.N().S(` create new instance of table `)
//line database_tpl.qtpl:478
	qw422016.E().S(cName)
//line database_tpl.qtpl:478
	qw422016.N().S(`
func (d *Database) New`)
//line database_tpl.qtpl:479
	qw422016.E().S(cName)
//line database_tpl.qtpl:479
	qw422016.N().S(`(ctx context.Context) (*`)
//line database_tpl.qtpl:479
	qw422016.E().S(cName)
//line database_tpl.qtpl:479
	qw422016.N().S(`, error) {
	const name = "`)
//line database_tpl.qtpl:480
	qw422016.E().S(name)
//line database_tpl.qtpl:480
	qw422016.N().S(`"
	table, ok := d.Tables[name]
    if !ok {
		var err error
		table, err = New`)
//line database_tpl.qtpl:484
	qw422016.E().S(cName)
//line database_tpl.qtpl:484
	qw422016.N().S(`FromConn(ctx, d.PsqlConn())
		if err != nil {
			return nil, err
		}
		d.Tables[name] = table
    }

    return &`)
//line database_tpl.qtpl:491
	qw422016.E().S(cName)
//line database_tpl.qtpl:491
	qw422016.N().S(`{
		Table: table.(*psql.Table),
    }, nil
}
`)
//line database_tpl.qtpl:495
}

//line database_tpl.qtpl:495
func (c *Creator) WriteCreateTableConstructor(qq422016 qtio422016.Writer, cName, name string) {
//line database_tpl.qtpl:495
	qw422016 := qt422016.AcquireWriter(qq422016)
//line database_tpl.qtpl:495
	c.StreamCreateTableConstructor(qw422016, cName, name)
//line database_tpl.qtpl:495
	qt422016.ReleaseWriter(qw422016)
//line database_tpl.qtpl:495
}

//line database_tpl.qtpl:495
func (c *Creator) CreateTableConstructor(cName, name string) string {
//line database_tpl.qtpl:495
	qb422016 := qt422016.AcquireByteBuffer()
//line database_tpl.qtpl:495
	c.WriteCreateTableConstructor(qb422016, cName, name)
//line database_tpl.qtpl:495
	qs422016 := string(qb422016.B)
//line database_tpl.qtpl:495
	qt422016.ReleaseByteBuffer(qb422016)
//line database_tpl.qtpl:495
	return qs422016
//line database_tpl.qtpl:495
}
