// Code generated by qtc from "routines.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line routines.qtpl:1
package _go

//line routines.qtpl:2
import (
	"fmt"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/ruslanBik4/dbEngine/dbEngine"
	"github.com/ruslanBik4/dbEngine/dbEngine/psql"
)

//line routines.qtpl:12
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line routines.qtpl:12
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line routines.qtpl:12
func (c *Creator) StreamCreateRoutinesInvoker(qw422016 *qt422016.Writer, r *psql.Routine, name string) {
//line routines.qtpl:14
	camelName := strcase.ToCamel(name)
	args := make([]any, len(r.Params()))
	sql, _, _ := r.BuildSql(dbEngine.ArgsForSelect(args...))

//line routines.qtpl:18
	if r.Type == psql.ROUTINE_TYPE_PROC {
//line routines.qtpl:18
		qw422016.N().S(`// `)
//line routines.qtpl:19
		qw422016.E().S(camelName)
//line routines.qtpl:19
		qw422016.N().S(` call procedure '`)
//line routines.qtpl:19
		qw422016.E().S(name)
//line routines.qtpl:19
		qw422016.N().S(`'
`)
//line routines.qtpl:20
		if r.Comment > "" {
//line routines.qtpl:20
			qw422016.N().S(`// DB comment: '`)
//line routines.qtpl:20
			qw422016.E().S(r.Comment)
//line routines.qtpl:20
			qw422016.N().S(`'`)
//line routines.qtpl:20
		}
//line routines.qtpl:20
		qw422016.N().S(`func (d *Database) `)
//line routines.qtpl:21
		qw422016.E().S(camelName)
//line routines.qtpl:21
		qw422016.N().S(`(
	ctx context.Context,`)
//line routines.qtpl:22
		c.streamparamsTitle(qw422016, r)
//line routines.qtpl:22
		qw422016.N().S(`
) error {
	return d.Conn.ExecDDL(
		ctx,
		`)
//line routines.qtpl:22
		qw422016.N().S("`")
//line routines.qtpl:26
		qw422016.E().S(sql)
//line routines.qtpl:26
		qw422016.N().S(``)
//line routines.qtpl:26
		qw422016.N().S("`")
//line routines.qtpl:26
		qw422016.N().S(`,
		`)
//line routines.qtpl:27
		c.streamparamsArgs(qw422016, r)
//line routines.qtpl:27
		qw422016.N().S(`)
}
`)
//line routines.qtpl:29
	} else {
//line routines.qtpl:30
		c.StreamCreateFunctionInvoker(qw422016, r, name, camelName, sql)
//line routines.qtpl:30
		qw422016.N().S(`
`)
//line routines.qtpl:31
	}
//line routines.qtpl:32
}

//line routines.qtpl:32
func (c *Creator) WriteCreateRoutinesInvoker(qq422016 qtio422016.Writer, r *psql.Routine, name string) {
//line routines.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line routines.qtpl:32
	c.StreamCreateRoutinesInvoker(qw422016, r, name)
//line routines.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line routines.qtpl:32
}

//line routines.qtpl:32
func (c *Creator) CreateRoutinesInvoker(r *psql.Routine, name string) string {
//line routines.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line routines.qtpl:32
	c.WriteCreateRoutinesInvoker(qb422016, r, name)
//line routines.qtpl:32
	qs422016 := string(qb422016.B)
//line routines.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line routines.qtpl:32
	return qs422016
//line routines.qtpl:32
}

// CreateRoutinesInvoker
//

//line routines.qtpl:34
func (c *Creator) StreamCreateFunctionInvoker(qw422016 *qt422016.Writer, r *psql.Routine, name, camelName, sql string) {
//line routines.qtpl:36
	typeReturn, initReturn, needReference := "", "", true

//line routines.qtpl:38
	switch len(r.Columns()) {
//line routines.qtpl:39
	case 0:
//line routines.qtpl:41
		typeReturn = c.udtToReturnType(r.UdtName)

//line routines.qtpl:43
	case 1:
//line routines.qtpl:45
		param := r.Columns()[0]
		typeReturn, _ = c.chkTypes(param, strcase.ToCamel(param.Name()))
		if a, ok := strings.CutPrefix(typeReturn, "[]"); param.BasicType() < 0 && ok {
			typeReturn = "WrapArray[*" + a + "]"
		}

//line routines.qtpl:51
	default:
//line routines.qtpl:52
		c.StreamCreateRowScanner(qw422016, r, camelName)
//line routines.qtpl:52
		qw422016.N().S(`
`)
//line routines.qtpl:54
		typeReturn = fmt.Sprintf("*%sRowScanner", camelName)
		initReturn = fmt.Sprintf("res = &%sRowScanner{}", camelName)
		needReference = false

//line routines.qtpl:58
	}
//line routines.qtpl:58
	qw422016.N().S(`// `)
//line routines.qtpl:59
	qw422016.E().S(camelName)
//line routines.qtpl:59
	qw422016.N().S(` run query with select DB function '`)
//line routines.qtpl:59
	qw422016.E().S(name)
//line routines.qtpl:59
	qw422016.N().S(`: `)
//line routines.qtpl:59
	qw422016.E().S(r.UdtName)
//line routines.qtpl:59
	qw422016.N().S(`'
`)
//line routines.qtpl:60
	if r.Comment > "" {
//line routines.qtpl:60
		qw422016.N().S(`// DB comment: '`)
//line routines.qtpl:60
		qw422016.E().S(r.Comment)
//line routines.qtpl:60
		qw422016.N().S(`'`)
//line routines.qtpl:60
	}
//line routines.qtpl:60
	qw422016.N().S(`// ATTENTION! It returns only 1 row `)
//line routines.qtpl:61
	qw422016.E().S(typeReturn)
//line routines.qtpl:61
	qw422016.N().S(`
func (d *Database) `)
//line routines.qtpl:62
	qw422016.E().S(camelName)
//line routines.qtpl:62
	qw422016.N().S(`(
	ctx context.Context,`)
//line routines.qtpl:63
	c.streamparamsTitle(qw422016, r)
//line routines.qtpl:63
	qw422016.N().S(`
) (res `)
//line routines.qtpl:64
	qw422016.E().S(typeReturn)
//line routines.qtpl:64
	qw422016.N().S(`, err error) {
	`)
//line routines.qtpl:65
	qw422016.N().S(initReturn)
//line routines.qtpl:65
	qw422016.N().S(`
	err = d.Conn.SelectOneAndScan(ctx,
		`)
//line routines.qtpl:67
	if needReference {
//line routines.qtpl:67
		qw422016.N().S(`&`)
//line routines.qtpl:67
	}
//line routines.qtpl:67
	qw422016.N().S(`res,
		`)
//line routines.qtpl:67
	qw422016.N().S("`")
//line routines.qtpl:68
	qw422016.E().S(sql)
//line routines.qtpl:68
	qw422016.N().S(`
		FETCH FIRST 1 ROW ONLY`)
//line routines.qtpl:68
	qw422016.N().S("`")
//line routines.qtpl:68
	qw422016.N().S(`,
		`)
//line routines.qtpl:70
	c.streamparamsArgs(qw422016, r)
//line routines.qtpl:70
	qw422016.N().S(`)

	return
}
`)
//line routines.qtpl:74
	if r.ReturnType() == "json" {
//line routines.qtpl:74
		qw422016.N().S(`// `)
//line routines.qtpl:75
		qw422016.E().S(camelName)
//line routines.qtpl:75
		qw422016.N().S(`Out run query with select DB function '`)
//line routines.qtpl:75
		qw422016.E().S(name)
//line routines.qtpl:75
		qw422016.N().S(`: `)
//line routines.qtpl:75
		qw422016.E().S(r.UdtName)
//line routines.qtpl:75
		qw422016.N().S(`'
`)
//line routines.qtpl:76
		if r.Comment > "" {
//line routines.qtpl:76
			qw422016.N().S(`// DB comment: '`)
//line routines.qtpl:76
			qw422016.E().S(r.Comment)
//line routines.qtpl:76
			qw422016.N().S(`'`)
//line routines.qtpl:76
		}
//line routines.qtpl:76
		qw422016.N().S(`// ATTENTION! It returns only 1 row `)
//line routines.qtpl:77
		qw422016.E().S(typeReturn)
//line routines.qtpl:77
		qw422016.N().S(`
func (d *Database) `)
//line routines.qtpl:78
		qw422016.E().S(camelName)
//line routines.qtpl:78
		qw422016.N().S(`Out(
	ctx context.Context,`)
//line routines.qtpl:79
		c.streamparamsTitle(qw422016, r)
//line routines.qtpl:79
		qw422016.N().S(`
	res any,
) error {
	 return d.Conn.SelectOneAndScan(ctx,
		&res,
		`)
//line routines.qtpl:79
		qw422016.N().S("`")
//line routines.qtpl:84
		qw422016.E().S(sql)
//line routines.qtpl:84
		qw422016.N().S(`
		FETCH FIRST 1 ROW ONLY`)
//line routines.qtpl:84
		qw422016.N().S("`")
//line routines.qtpl:84
		qw422016.N().S(`,
		`)
//line routines.qtpl:86
		c.streamparamsArgs(qw422016, r)
//line routines.qtpl:86
		qw422016.N().S(`)
}
`)
//line routines.qtpl:88
	}
//line routines.qtpl:89
	if r.ReturnType() == "record" {
//line routines.qtpl:90
		typeReturn = fmt.Sprintf("%sRowScanner", camelName)

//line routines.qtpl:90
		qw422016.N().S(`// `)
//line routines.qtpl:91
		qw422016.E().S(camelName)
//line routines.qtpl:91
		qw422016.N().S(`Each run query with select DB function '`)
//line routines.qtpl:91
		qw422016.E().S(name)
//line routines.qtpl:91
		qw422016.N().S(`'
`)
//line routines.qtpl:92
		if r.Comment > "" {
//line routines.qtpl:92
			qw422016.N().S(`// DB comment: '`)
//line routines.qtpl:92
			qw422016.E().S(r.Comment)
//line routines.qtpl:92
			qw422016.N().S(`'`)
//line routines.qtpl:92
		}
//line routines.qtpl:92
		qw422016.N().S(`// each will get every row from &`)
//line routines.qtpl:93
		qw422016.E().S(camelName)
//line routines.qtpl:93
		qw422016.N().S(`sRowScanner
func (d *Database) `)
//line routines.qtpl:94
		qw422016.E().S(camelName)
//line routines.qtpl:94
		qw422016.N().S(`Each(
	ctx context.Context,
	each func(record *`)
//line routines.qtpl:96
		qw422016.E().S(typeReturn)
//line routines.qtpl:96
		qw422016.N().S(`) error,`)
//line routines.qtpl:96
		c.streamparamsTitle(qw422016, r)
//line routines.qtpl:96
		qw422016.N().S(`
) error {
	res := &`)
//line routines.qtpl:98
		qw422016.E().S(typeReturn)
//line routines.qtpl:98
		qw422016.N().S(`{}
	err := d.Conn.SelectAndScanEach(ctx,
		func() error {
			defer func() {
			//	create new record
				*res = `)
//line routines.qtpl:103
		qw422016.E().S(typeReturn)
//line routines.qtpl:103
		qw422016.N().S(`{}
			}()

			if each != nil {
				return each(res)
			}
			return nil
		},
		res,
		`)
//line routines.qtpl:103
		qw422016.N().S("`")
//line routines.qtpl:112
		qw422016.E().S(sql)
//line routines.qtpl:112
		qw422016.N().S(``)
//line routines.qtpl:112
		qw422016.N().S("`")
//line routines.qtpl:112
		qw422016.N().S(`,
		`)
//line routines.qtpl:113
		c.streamparamsArgs(qw422016, r)
//line routines.qtpl:113
		qw422016.N().S(`)

	return err
}

// `)
//line routines.qtpl:118
		qw422016.E().S(camelName)
//line routines.qtpl:118
		qw422016.N().S(`All run query with select DB function '`)
//line routines.qtpl:118
		qw422016.E().S(name)
//line routines.qtpl:118
		qw422016.N().S(`'
`)
//line routines.qtpl:119
		if r.Comment > "" {
//line routines.qtpl:119
			qw422016.N().S(`// DB comment: '`)
//line routines.qtpl:119
			qw422016.E().S(r.Comment)
//line routines.qtpl:119
			qw422016.N().S(`'`)
//line routines.qtpl:119
		}
//line routines.qtpl:119
		qw422016.N().S(`// WARNING! It return ALL rows as Slice of &`)
//line routines.qtpl:120
		qw422016.E().S(camelName)
//line routines.qtpl:120
		qw422016.N().S(`sRowScanner
func (d *Database) `)
//line routines.qtpl:121
		qw422016.E().S(camelName)
//line routines.qtpl:121
		qw422016.N().S(`All(
	ctx context.Context,`)
//line routines.qtpl:122
		c.streamparamsTitle(qw422016, r)
//line routines.qtpl:122
		qw422016.N().S(`
) (res []`)
//line routines.qtpl:123
		qw422016.E().S(typeReturn)
//line routines.qtpl:123
		qw422016.N().S(`, err error) {
	buf := `)
//line routines.qtpl:124
		qw422016.E().S(typeReturn)
//line routines.qtpl:124
		qw422016.N().S(`{}
	err = d.Conn.SelectAndScanEach(ctx,
		func() error {
			res = append(res, buf)
			//	create new record
			buf = `)
//line routines.qtpl:129
		qw422016.E().S(typeReturn)
//line routines.qtpl:129
		qw422016.N().S(`{}

			return nil
		},
		&buf,
		`)
//line routines.qtpl:129
		qw422016.N().S("`")
//line routines.qtpl:134
		qw422016.E().S(sql)
//line routines.qtpl:134
		qw422016.N().S(``)
//line routines.qtpl:134
		qw422016.N().S("`")
//line routines.qtpl:134
		qw422016.N().S(`,
		`)
//line routines.qtpl:135
		c.streamparamsArgs(qw422016, r)
//line routines.qtpl:135
		qw422016.N().S(`)

	return
}
`)
//line routines.qtpl:139
	}
//line routines.qtpl:139
	qw422016.N().S(`
`)
//line routines.qtpl:140
}

//line routines.qtpl:140
func (c *Creator) WriteCreateFunctionInvoker(qq422016 qtio422016.Writer, r *psql.Routine, name, camelName, sql string) {
//line routines.qtpl:140
	qw422016 := qt422016.AcquireWriter(qq422016)
//line routines.qtpl:140
	c.StreamCreateFunctionInvoker(qw422016, r, name, camelName, sql)
//line routines.qtpl:140
	qt422016.ReleaseWriter(qw422016)
//line routines.qtpl:140
}

//line routines.qtpl:140
func (c *Creator) CreateFunctionInvoker(r *psql.Routine, name, camelName, sql string) string {
//line routines.qtpl:140
	qb422016 := qt422016.AcquireByteBuffer()
//line routines.qtpl:140
	c.WriteCreateFunctionInvoker(qb422016, r, name, camelName, sql)
//line routines.qtpl:140
	qs422016 := string(qb422016.B)
//line routines.qtpl:140
	qt422016.ReleaseByteBuffer(qb422016)
//line routines.qtpl:140
	return qs422016
//line routines.qtpl:140
}

// CreateFunctionInvoker
//

//line routines.qtpl:142
func (c *Creator) StreamCreateRowScanner(qw422016 *qt422016.Writer, r *psql.Routine, camelName string) {
//line routines.qtpl:142
	qw422016.N().S(`
// `)
//line routines.qtpl:144
	qw422016.E().S(camelName)
//line routines.qtpl:144
	qw422016.N().S(`RowScanner run query with select
type `)
//line routines.qtpl:145
	qw422016.E().S(camelName)
//line routines.qtpl:145
	qw422016.N().S(`RowScanner struct {
`)
//line routines.qtpl:147
	maxLen := 0
	for _, param := range r.Columns() {
		maxLen = max(maxLen, len(param.Name()))
	}

//line routines.qtpl:152
	for _, param := range r.Columns() {
//line routines.qtpl:154
		s := strcase.ToCamel(param.Name())
		typeCol, _ := c.chkTypes(param, s)
		if a, ok := strings.CutPrefix(typeCol, "[]"); param.BasicType() < 0 && ok {
			typeCol = "WrapArray[*" + a + "]"
		}

//line routines.qtpl:159
		qw422016.N().S(`	`)
//line routines.qtpl:160
		qw422016.E().S(fmt.Sprintf("%-[2]*[1]s ", s, maxLen))
//line routines.qtpl:160
		qw422016.E().S(typeCol)
//line routines.qtpl:160
		qw422016.E().S("\t\t")
//line routines.qtpl:160
		qw422016.N().S(``)
//line routines.qtpl:160
		qw422016.N().S("`")
//line routines.qtpl:160
		qw422016.N().S(`json:"`)
//line routines.qtpl:160
		qw422016.E().S(param.Name())
//line routines.qtpl:160
		qw422016.N().S(`"`)
//line routines.qtpl:160
		qw422016.N().S("`")
//line routines.qtpl:160
		qw422016.N().S(`
`)
//line routines.qtpl:161
	}
//line routines.qtpl:161
	qw422016.N().S(`}

// GetFields implement dbEngine.RowScanner interface
func (r *`)
//line routines.qtpl:165
	qw422016.E().S(camelName)
//line routines.qtpl:165
	qw422016.N().S(`RowScanner) GetFields(columns []dbEngine.Column) []any {
	v := make([]any, len(columns))
	for i, col := range columns {
		switch col.Name() {
`)
//line routines.qtpl:169
	for _, param := range r.Columns() {
//line routines.qtpl:169
		qw422016.N().S(`		case "`)
//line routines.qtpl:170
		qw422016.E().S(param.Name())
//line routines.qtpl:170
		qw422016.N().S(`":
			v[i] = &r.`)
//line routines.qtpl:171
		qw422016.N().S(strcase.ToCamel(param.Name()))
//line routines.qtpl:171
		qw422016.N().S(`
`)
//line routines.qtpl:172
	}
//line routines.qtpl:172
	qw422016.N().S(`		}
	}

	return v
}
`)
//line routines.qtpl:178
}

//line routines.qtpl:178
func (c *Creator) WriteCreateRowScanner(qq422016 qtio422016.Writer, r *psql.Routine, camelName string) {
//line routines.qtpl:178
	qw422016 := qt422016.AcquireWriter(qq422016)
//line routines.qtpl:178
	c.StreamCreateRowScanner(qw422016, r, camelName)
//line routines.qtpl:178
	qt422016.ReleaseWriter(qw422016)
//line routines.qtpl:178
}

//line routines.qtpl:178
func (c *Creator) CreateRowScanner(r *psql.Routine, camelName string) string {
//line routines.qtpl:178
	qb422016 := qt422016.AcquireByteBuffer()
//line routines.qtpl:178
	c.WriteCreateRowScanner(qb422016, r, camelName)
//line routines.qtpl:178
	qs422016 := string(qb422016.B)
//line routines.qtpl:178
	qt422016.ReleaseByteBuffer(qb422016)
//line routines.qtpl:178
	return qs422016
//line routines.qtpl:178
}

//line routines.qtpl:180
func (c *Creator) streamparamsTitle(qw422016 *qt422016.Writer, r *psql.Routine) {
//line routines.qtpl:182
	maxLen := 0
	for _, param := range r.Params() {
		maxLen = max(maxLen, len(param.Name()))
	}

//line routines.qtpl:186
	qw422016.N().S(`	`)
//line routines.qtpl:187
	for _, param := range r.Params() {
//line routines.qtpl:187
		qw422016.N().S(`
`)
//line routines.qtpl:189
		s := strcase.ToLowerCamel(param.Name())
		typeCol, _ := c.chkTypes(param, s)
		if param.Default() != nil && !strings.HasPrefix(typeCol, "[]") {
			typeCol = "*" + typeCol
		}

//line routines.qtpl:194
		qw422016.N().S(`	`)
//line routines.qtpl:195
		qw422016.E().S(fmt.Sprintf("%-[2]*[1]s ", s, maxLen))
//line routines.qtpl:195
		qw422016.E().S(typeCol)
//line routines.qtpl:195
		qw422016.N().S(`, // `)
//line routines.qtpl:195
		qw422016.E().S(param.Comment())
//line routines.qtpl:195
		qw422016.N().S(` pg type: `)
//line routines.qtpl:195
		qw422016.E().S(param.Type())
//line routines.qtpl:195
		if param.Default() != nil {
//line routines.qtpl:195
			qw422016.N().S(`def: `)
//line routines.qtpl:195
			qw422016.E().V(param.Default())
//line routines.qtpl:195
		}
//line routines.qtpl:196
	}
//line routines.qtpl:197
}

//line routines.qtpl:197
func (c *Creator) writeparamsTitle(qq422016 qtio422016.Writer, r *psql.Routine) {
//line routines.qtpl:197
	qw422016 := qt422016.AcquireWriter(qq422016)
//line routines.qtpl:197
	c.streamparamsTitle(qw422016, r)
//line routines.qtpl:197
	qt422016.ReleaseWriter(qw422016)
//line routines.qtpl:197
}

//line routines.qtpl:197
func (c *Creator) paramsTitle(r *psql.Routine) string {
//line routines.qtpl:197
	qb422016 := qt422016.AcquireByteBuffer()
//line routines.qtpl:197
	c.writeparamsTitle(qb422016, r)
//line routines.qtpl:197
	qs422016 := string(qb422016.B)
//line routines.qtpl:197
	qt422016.ReleaseByteBuffer(qb422016)
//line routines.qtpl:197
	return qs422016
//line routines.qtpl:197
}

//line routines.qtpl:199
func (c *Creator) streamparamsArgs(qw422016 *qt422016.Writer, r *psql.Routine) {
//line routines.qtpl:200
	for _, param := range r.Params() {
//line routines.qtpl:200
		qw422016.N().S(`	`)
//line routines.qtpl:201
		qw422016.E().S(strcase.ToLowerCamel(param.Name()))
//line routines.qtpl:201
		qw422016.N().S(`,
`)
//line routines.qtpl:202
	}
//line routines.qtpl:203
}

//line routines.qtpl:203
func (c *Creator) writeparamsArgs(qq422016 qtio422016.Writer, r *psql.Routine) {
//line routines.qtpl:203
	qw422016 := qt422016.AcquireWriter(qq422016)
//line routines.qtpl:203
	c.streamparamsArgs(qw422016, r)
//line routines.qtpl:203
	qt422016.ReleaseWriter(qw422016)
//line routines.qtpl:203
}

//line routines.qtpl:203
func (c *Creator) paramsArgs(r *psql.Routine) string {
//line routines.qtpl:203
	qb422016 := qt422016.AcquireByteBuffer()
//line routines.qtpl:203
	c.writeparamsArgs(qb422016, r)
//line routines.qtpl:203
	qs422016 := string(qb422016.B)
//line routines.qtpl:203
	qt422016.ReleaseByteBuffer(qb422016)
//line routines.qtpl:203
	return qs422016
//line routines.qtpl:203
}
